// app-react/src/components/statutory/sections/directors/ResignDirectorModal.tsx
import React, { useState } from 'react';
import { Modal, Button, Form } from 'react-bootstrap';

interface ResignDirectorModalProps {
  show: boolean;
  onHide: () => void;
  director: {
    title: string;
    firstName: string;
    lastName: string;
    directorType: string;
  };
  onConfirm: (date: string) => void;
}

const ResignDirectorModal: React.FC<ResignDirectorModalProps> = ({
  show,
  onHide,
  director,
  onConfirm
}) => {
  const [step, setStep] = useState(1);
  const [resignationDate, setResignationDate] = useState(
    new Date().toISOString().split('T')[0]
  );

  const handleNext = () => {
    setStep(2);
  };

  const handleBack = () => {
    setStep(1);
  };

  const handleConfirm = () => {
    onConfirm(resignationDate);
  };

  const handleClose = () => {
    setStep(1);
    onHide();
  };

  return (
    <Modal show={show} onHide={handleClose}>
      <Modal.Header closeButton>
        <Modal.Title>
          {step === 1 ? 'Resign Director' : 'Confirm Resignation'}
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        {step === 1 ? (
          <>
            <div className="alert alert-warning">
              <i className="bi bi-exclamation-triangle me-2"></i>
              You are about to resign the following director:
            </div>
            <div className="mb-4">
              <p className="mb-2">
                <strong>Name:</strong>{' '}
                {`${director.title} ${director.firstName} ${director.lastName}`}
              </p>
              <p className="mb-2">
                <strong>Position:</strong> {director.directorType}
              </p>
            </div>
            <Form.Group className="mb-3">
              <Form.Label>Resignation Date</Form.Label>
              <Form.Control
                type="date"
                value={resignationDate}
                onChange={(e) => setResignationDate(e.target.value)}
              />
            </Form.Group>
          </>
        ) : (
          <div className="alert alert-danger">
            <i className="bi bi-exclamation-triangle-fill me-2"></i>
            <strong>Please confirm:</strong>
            <p className="mt-2 mb-0">
              This action will mark{' '}
              {`${director.title} ${director.firstName} ${director.lastName}`} as
              resigned from {new Date(resignationDate).toLocaleDateString()}. This
              action cannot be undone.
            </p>
          </div>
        )}
      </Modal.Body>
      <Modal.Footer>
        {step === 1 ? (
          <>
            <Button variant="secondary" onClick={handleClose}>
              Cancel
            </Button>
            <Button variant="primary" onClick={handleNext}>
              Next
            </Button>
          </>
        ) : (
          <>
            <Button variant="secondary" onClick={handleBack}>
              Back
            </Button>
            <Button variant="danger" onClick={handleConfirm}>
              Confirm Resignation
            </Button>
          </>
        )}
      </Modal.Footer>
    </Modal>
  );
};

export default ResignDirectorModal;

// app/src/app/components/statutory/directors/modal/resign-director-modal.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { Director } from '../../statutory.types';

@Component({
  selector: 'app-resign-director-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="modal-header">
      <h5 class="modal-title">Director Resignation</h5>
      <button type="button" class="btn-close" (click)="activeModal.dismiss()"></button>
    </div>

    <div class="modal-body">
      <div class="alert alert-warning mb-4">
        <i class="bi bi-exclamation-triangle me-2"></i>
        Are you sure you want to mark <strong>{{ getFullName(director) }}</strong> as resigned?
      </div>

      <form [formGroup]="resignForm">
        <div class="mb-3">
          <label class="form-label">Resignation Date</label>
          <input type="date" class="form-control" formControlName="resignationDate">
          <div class="invalid-feedback" [class.d-block]="resignForm.get('resignationDate')?.errors?.['required'] && resignForm.get('resignationDate')?.touched">
            Resignation date is required
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Reason for Resignation</label>
          <textarea class="form-control" rows="3" formControlName="reason" placeholder="Enter reason for resignation"></textarea>
          <div class="invalid-feedback" [class.d-block]="resignForm.get('reason')?.errors?.['required'] && resignForm.get('reason')?.touched">
            Reason is required
          </div>
        </div>
      </form>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-link" (click)="activeModal.dismiss()">Cancel</button>
      <button type="button" class="btn btn-primary" (click)="onSubmit()" [disabled]="!resignForm.valid">
        Confirm Resignation
      </button>
    </div>
  `
})
export class ResignDirectorModalComponent {
  @Input() director!: Director;
  resignForm: FormGroup;

  constructor(
    public activeModal: NgbActiveModal,
    private fb: FormBuilder
  ) {
    this.resignForm = this.fb.group({
      resignationDate: [new Date().toISOString().split('T')[0], Validators.required],
      reason: ['', Validators.required]
    });
  }

  getFullName(director: Director): string {
    return `${director.title} ${director.firstName} ${director.lastName}`;
  }

  onSubmit(): void {
    if (this.resignForm.valid) {
      const resignationDetails = {
        ...this.director,
        status: 'Resigned' as const,
        resignationDate: this.resignForm.value.resignationDate,
        resignationReason: this.resignForm.value.reason
      };
      this.activeModal.close(resignationDetails);
    } else {
      Object.keys(this.resignForm.controls).forEach(key => {
        const control = this.resignForm.get(key);
        if (control?.invalid) {
          control.markAsTouched();
        }
      });
    }
  }
}
