// app/src/app/components/statutory/statutory-sidebar/statutory-sidebar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

interface NavItem {
  label: string;
  route: string;
  icon: string;
}

@Component({
  selector: 'app-statutory-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './statutory-sidebar.component.html',
  styleUrls: ['./statutory-sidebar.component.scss']
})
export class StatutorySidebarComponent {
  navItems: NavItem[] = [
    {
      label: 'Dashboard',
      route: '/statutory/dashboard',
      icon: 'bi-speedometer2'
    },
    {
      label: 'Directors & Secretaries',
      route: '/statutory/directors',
      icon: 'bi-person-badge'
    },
    {
      label: 'Members (Shareholders)',
      route: '/statutory/shareholders',
      icon: 'bi-people'
    },
    {
      label: 'Share Register',
      route: '/statutory/shares',
      icon: 'bi-journal-bookmark'
    },
    {
      label: 'Beneficial Owners',
      route: '/statutory/beneficial-owners',
      icon: 'bi-person-check'
    },
    {
      label: 'Charges Register',
      route: '/statutory/charges',
      icon: 'bi-bank'
    },
    {
      label: 'Share Allotments',
      route: '/statutory/allotments',
      icon: 'bi-plus-circle'
    },
    {
      label: 'General Meetings',
      route: '/statutory/meetings',
      icon: 'bi-calendar-event'
    },
    {
      label: 'Board Minutes',
      route: '/statutory/board-minutes',
      icon: 'bi-file-text'
    }
  ];
}

<div class="nav-section">
  <div class="section-header">
    <span>STATUTORY REGISTERS</span>
  </div>
  <ul class="nav-items">
    <li *ngFor="let item of navItems">
      <a [routerLink]="item.route" 
         routerLinkActive="active">
        <i class="bi" [class]="item.icon"></i>
        <span class="nav-label">{{ item.label }}</span>
      </a>
    </li>
  </ul>
</div>

// app-react/src/components/statutory/StatutorySidebar.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

interface StatutorySidebarProps {
  isExpanded?: boolean;
}

const StatutorySidebar: React.FC<StatutorySidebarProps> = ({ isExpanded = true }) => {
  const navItems = [
    {
      label: 'Dashboard',
      icon: 'bi-grid',
      route: '/statutory/dashboard'
    },
    {
      label: 'Directors & Secretaries',
      icon: 'bi-person-badge',
      route: '/statutory/directors'
    },
    {
      label: 'Members Register',
      icon: 'bi-people',
      route: '/statutory/shareholders'
    },
    {
      label: 'Share Register',
      icon: 'bi-journal-bookmark',
      route: '/statutory/shares'
    },
    {
      label: 'Beneficial Owners',
      icon: 'bi-person-check',
      route: '/statutory/beneficial-owners'
    },
    {
      label: 'Charges Register',
      icon: 'bi-bank',
      route: '/statutory/charges'
    },
    {
      label: 'Share Allotments',
      icon: 'bi-plus-circle',
      route: '/statutory/allotments'
    },
    {
      label: 'General Meetings',
      icon: 'bi-calendar-event',
      route: '/statutory/meetings'
    },
    {
      label: 'Board Minutes',
      icon: 'bi-file-text',
      route: '/statutory/board-minutes'
    }
  ];

  return (
    <div className="d-flex flex-column h-100">
      <div className="py-4">
        {isExpanded && (
          <div className="px-4 mb-2">
            <span className="text-uppercase small fw-semibold text-secondary">STATUTORY REGISTERS</span>
          </div>
        )}
        <ul className="nav flex-column">
          {navItems.map((item) => (
            <li className="nav-item" key={item.route}>
              <NavLink
                to={item.route}
                className={({ isActive }) => `
                  nav-link d-flex align-items-center py-2
                  ${isExpanded ? 'px-4' : 'px-2'}
                  ${isActive ? 'active bg-primary-subtle text-primary fw-medium' : ''}
                  hover-primary
                `}
                end={item.route === '/statutory/dashboard'}
              >
                <i className={`bi fs-5 ${isExpanded ? 'me-3' : ''} ${item.icon}`}></i>
                {isExpanded && <span className="small">{item.label}</span>}
              </NavLink>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default StatutorySidebar;
