// app/src/app/components/statutory/directors/directors.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, from, of, forkJoin } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, filter, map } from 'rxjs/operators';

import { CreateDirectorModalComponent } from './modal/create-director-modal.component';
import { EditDirectorModalComponent } from './modal/edit-director-modal.component';
import { ViewDirectorModalComponent } from './modal/view-director-modal.component';
import { ResignDirectorModalComponent } from './modal/resign-director-modal.component';
import { ConfirmModalComponent } from '../../../components/settings/users/modal/confirm-modal.component';

import { DirectorService } from '../../../services/statutory/director.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { CompanyService } from '../../../services/settings/company.service';
import { AuthService } from '../../../services/auth/auth.service';
import { Director, Activity } from '../statutory.types';
import type { Company } from '../../../components/settings/settings.types';

interface ActivityResponse {
  activities: Activity[];
  total: number;
}

@Component({
  selector: 'app-directors',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateDirectorModalComponent,
    EditDirectorModalComponent,
    ViewDirectorModalComponent,
    ResignDirectorModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Error Alert -->
      <div class="alert alert-danger alert-dismissible fade show" role="alert" *ngIf="error">
        {{ error }}
        <button type="button" class="btn-close" (click)="error = null"></button>
      </div>

      <!-- Loading State -->
      <div class="text-center py-5" *ngIf="loading">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>

      <!-- Content (only show when not loading) -->
      <ng-container *ngIf="!loading">
        <!-- Header -->
        <div class="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 class="h3 mb-2">Directors Register</h1>
            <p class="text-muted mb-0">Record and manage company directors and their appointments</p>
          </div>
          <div>
            <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddDirectorModal()">
              <i class="bi bi-plus-lg"></i>
              <span>Add Director</span>
            </button>
          </div>
        </div>

        <!-- Metrics -->
        <div class="row g-3 mb-4">
          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Active Directors</span>
                  <i class="bi bi-people fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getActiveDirectorsCount() }}</h3>
                <small class="text-muted">Currently serving directors</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Executive Directors</span>
                  <i class="bi bi-person-badge fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getExecutiveDirectorsCount() }}</h3>
                <small class="text-muted">Executive & Managing Directors</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Non-Executive Directors</span>
                  <i class="bi bi-person-check fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getNonExecutiveDirectorsCount() }}</h3>
                <small class="text-muted">Independent & Non-Executive Directors</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Average Tenure</span>
                  <i class="bi bi-calendar-check fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getAverageTenure() }}</h3>
                <small class="text-muted">years</small>
              </div>
            </div>
          </div>
        </div>

        <!-- Directors Table -->
        <div class="card mb-4">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Current Directors</h5>
            <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAllDirectors()">
              <i [class]="showAllDirectors ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
              <span>{{ showAllDirectors ? 'Show Active Only' : 'Show All Directors' }}</span>
            </button>
          </div>
          <div class="table-responsive">
            <table class="table table-hover mb-0">
              <thead class="bg-light">
                <tr>
                  <th class="text-uppercase small fw-semibold text-secondary">Name</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Company</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Type</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Appointed</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Service</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Shareholding</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let director of getFilteredDirectors()">
                  <td>
                    <div class="d-flex align-items-center gap-2">
                      <i class="bi bi-person-circle text-secondary"></i>
                      <a href="#" class="text-decoration-none" (click)="viewDirector(director, $event)">
                        {{ getFullName(director) }}
                      </a>
                    </div>
                  </td>
                  <td>{{ director.company?.name }}</td>
                  <td>{{ director.directorType }}</td>
                  <td>{{ formatDate(director.appointmentDate) }}</td>
                  <td>{{ getServiceDuration(director.appointmentDate, director.resignationDate) }}</td>
                  <td>{{ director.shareholding || 'None' }}</td>
                  <td>
                    <span [class]="'badge ' + (director.status === 'Active' ? 'text-bg-success' : 'text-bg-secondary')">
                      {{ director.status }}
                    </span>
                  </td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-link btn-sm text-body px-2" (click)="viewDirector(director)" title="View Details">
                        <i class="bi bi-eye"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-body px-2" (click)="editDirector(director)" title="Edit">
                        <i class="bi bi-pencil"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-body px-2" *ngIf="director.status === 'Active'" (click)="markAsResigned(director)" title="Mark as Resigned">
                        <i class="bi bi-person-dash"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-danger px-2" (click)="removeDirector(director)" title="Remove">
                        <i class="bi bi-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                <tr *ngIf="getFilteredDirectors().length === 0">
                  <td colspan="8" class="text-center py-4 text-muted">
                    <i class="bi bi-info-circle me-2"></i>
                    No directors found
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Recent Activities -->
        <div class="card">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Recent Activities</h5>
            <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
              <i class="bi bi-arrow-clockwise me-1"></i>
              <span>Refresh</span>
            </button>
          </div>
          <div class="card-body">
            <div class="list-group list-group-flush">
              <div class="list-group-item px-0" *ngFor="let activity of recentActivities">
                <div class="d-flex align-items-start gap-3">
                  <div class="bg-light rounded p-2">
                    <i [class]="getActivityIcon(activity.type)"></i>
                  </div>
                  <div>
                    <p class="mb-1">{{ activity.description }}</p>
                    <div class="d-flex align-items-center gap-2 small">
                      <span class="text-primary">{{ activity.user }}</span>
                      <span class="text-muted">{{ activity.time }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
                <i class="bi bi-info-circle me-2"></i>
                No recent activities
              </div>
            </div>
          </div>
        </div>
      </ng-container>
    </div>
  `
})
export class DirectorsComponent implements OnInit, OnDestroy {
  directors: Director[] = [];
  showAllDirectors = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();
  private accessibleCompanies: Company[] = [];

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private directorService: DirectorService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's directors
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.directorService.getDirectors(companyId, this.showAllDirectors ? undefined : 'Active').pipe(
          map(directors => directors.map(d => ({ ...d, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading directors:', error);
        this.error = 'Failed to load directors. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(directorsArrays => {
      this.directors = directorsArrays.flat();
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'director',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }

  openAddDirectorModal(): void {
    const modalRef = this.modalService.open(CreateDirectorModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.componentInstance.companies = this.accessibleCompanies;

    modalRef.result.then(
      (result: { company: Company; director: Omit<Director, 'id'> }) => {
        this.directorService.createDirector(result.company.id, result.director)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create director. Please try again.';
              console.error('Error creating director:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(director => {
              if (director) {
                this.directors.push({ ...director, company: result.company });
                return this.addActivity(result.company.id, {
                  type: 'appointment',
                  entityType: 'director',
                  entityId: director.id,
                  description: `${this.getFullName(director)} appointed as ${director.directorType}`,
                  user: 'System'
                }).pipe(map(() => director));
              }
              return of(null);
            })
          )
          .subscribe(director => {
            if (director) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeDirector(director: Director): void {
    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove ${this.getFullName(director)} from the directors register?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.directorService.deleteDirector(director.companyId, director.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove director. Please try again.';
                console.error('Error removing director:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                const index = this.directors.findIndex(d => d.id === director.id);
                if (index !== -1) {
                  this.directors.splice(index, 1);
                  return this.addActivity(director.companyId, {
                    type: 'removal',
                    entityType: 'director',
                    entityId: director.id,
                    description: `${this.getFullName(director)} removed from directors register`,
                    user: 'System'
                  });
                }
                return of(null);
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-GB');
  }

  getFullName(director: Director): string {
    return `${director.title} ${director.firstName} ${director.lastName}`;
  }

  markAsResigned(director: Director): void {
    const modalRef = this.modalService.open(ResignDirectorModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.director = {...director};
    
    modalRef.result.then(
      (updatedDirector: Director & { resignationReason: string }) => {
        const resignationDate = updatedDirector.resignationDate || new Date().toISOString();
        this.directorService.resignDirector(director.companyId, director.id, resignationDate)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to resign director. Please try again.';
              console.error('Error resigning director:', error);
              this.error = errorMsg;
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              const index = this.directors.findIndex(d => d.id === director.id);
              if (index !== -1) {
                this.directors[index] = { ...result, company: director.company };
                this.addActivity(director.companyId, {
                  type: 'resignation',
                  entityType: 'director',
                  entityId: director.id,
                  description: `${this.getFullName(director)} resigned from position of ${director.directorType}`,
                  user: 'System'
                });
                this.refreshData();
              }
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  getServiceDuration(appointmentDate: string, resignationDate?: string): string {
    const start = new Date(appointmentDate);
    const end = resignationDate ? new Date(resignationDate) : new Date();
    const diffTime = Math.abs(end.getTime() - start.getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    const years = Math.floor(diffDays / 365);
    const months = Math.floor((diffDays % 365) / 30);
    
    if (years === 0) {
      return `${months} month${months !== 1 ? 's' : ''}`;
    }
    return `${years} year${years !== 1 ? 's' : ''} ${months} month${months !== 1 ? 's' : ''}`;
  }

  getActiveDirectorsCount(): number {
    return this.directors.filter(d => d.status === 'Active').length;
  }

  getExecutiveDirectorsCount(): number {
    return this.directors.filter(d => 
      d.status === 'Active' && 
      (d.directorType === 'Executive Director' || d.directorType === 'Managing Director')
    ).length;
  }

  getNonExecutiveDirectorsCount(): number {
    return this.directors.filter(d => 
      d.status === 'Active' && 
      (d.directorType === 'Non-Executive Director' || d.directorType === 'Independent Director')
    ).length;
  }

  getAverageTenure(): string {
    const activeDirectors = this.directors.filter(d => d.status === 'Active');
    if (activeDirectors.length === 0) return '0';

    const totalDays = activeDirectors.reduce((sum, director) => {
      const start = new Date(director.appointmentDate);
      const end = new Date();
      return sum + Math.ceil(Math.abs(end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
    }, 0);

    const averageYears = (totalDays / 365 / activeDirectors.length).toFixed(1);
    return averageYears;
  }

  toggleShowAllDirectors(): void {
    this.showAllDirectors = !this.showAllDirectors;
    this.refreshData();
  }

  getFilteredDirectors(): Director[] {
    return this.showAllDirectors 
      ? this.directors 
      : this.directors.filter(d => d.status === 'Active');
  }

  viewDirector(director: Director, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewDirectorModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.director = {...director};
    
    modalRef.result.then(
      (result: { action: string; director: Director } | undefined) => {
        if (result?.action === 'edit') {
          this.editDirector(result.director);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editDirector(director: Director, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(EditDirectorModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.director = {...director};
    modalRef.componentInstance.companies = this.accessibleCompanies;
    modalRef.componentInstance.mode = 'edit';
    
    modalRef.result.then(
      (updatedDirector: Director) => {
        this.directorService.updateDirector(director.companyId, director.id, updatedDirector)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update director. Please try again.';
              console.error('Error updating director:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                const index = this.directors.findIndex(d => d.id === director.id);
                if (index !== -1) {
                  this.directors[index] = { ...result, company: director.company };
                  return this.addActivity(director.companyId, {
                    type: 'update',
                    entityType: 'director',
                    entityId: director.id,
                    description: `${this.getFullName(director)} details updated`,
                    user: 'System'
                  }).pipe(map(() => result));
                }
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'appointment':
        return 'bi bi-person-plus';
      case 'resignation':
        return 'bi bi-person-dash';
      case 'update':
        return 'bi bi-pencil';
      case 'removal':
        return 'bi bi-trash';
      default:
        return 'bi bi-activity';
    }
  }
}

<div class="directors">
  <div class="container-fluid p-4">
    <!-- Header -->
    <div class="page-header d-flex justify-content-between align-items-center mb-4">
      <div>
        <h1>Directors Register</h1>
        <p class="text-muted mb-0">Record and manage company directors and their appointments</p>
      </div>
      <button class="btn btn-primary" (click)="openAddDirectorModal()">
        <i class="bi bi-plus-lg me-2"></i>
        Add Director
      </button>
    </div>

    <!-- Metrics -->
    <div class="row g-4 mb-4">
      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Active Directors</span>
            <i class="bi bi-people"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getActiveDirectorsCount() }}</div>
            <div class="metric-details">Currently serving directors</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Executive Directors</span>
            <i class="bi bi-person-badge"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getExecutiveDirectorsCount() }}</div>
            <div class="metric-details">Executive & Managing Directors</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Non-Executive Directors</span>
            <i class="bi bi-person-check"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getNonExecutiveDirectorsCount() }}</div>
            <div class="metric-details">Independent & Non-Executive Directors</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Average Tenure</span>
            <i class="bi bi-calendar-check"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getAverageTenure() }}</div>
            <div class="metric-details">years</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Directors Table -->
    <div class="card mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Current Directors</h5>
        <button class="btn btn-link" (click)="toggleShowAllDirectors()">
          {{ showAllDirectors ? 'Show Active Only' : 'Show All Directors' }}
        </button>
      </div>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>NAME</th>
              <th>TYPE</th>
              <th>APPOINTED</th>
              <th>SERVICE</th>
              <th>SHAREHOLDING</th>
              <th>STATUS</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let director of getFilteredDirectors(); let i = index">
              <td>
                <a href="#" class="director-name" (click)="viewDirectorDetails(director, $event)">
                  {{ getFullName(director) }}
                </a>
              </td>
              <td>{{ director.directorType }}</td>
              <td>{{ formatDate(director.appointmentDate) }}</td>
              <td>{{ getServiceDuration(director.appointmentDate, director.resignationDate) }}</td>
              <td>{{ director.shareholding || 'None' }}</td>
              <td>
                <span class="status-badge" [class.active]="director.status === 'Active'" [class.resigned]="director.status === 'Resigned'">
                  {{ director.status }}
                </span>
              </td>
              <td>
                <div class="btn-group">
                  <button class="btn btn-link" (click)="viewDirectorDetails(director, $event)" title="View Details">
                    <i class="bi bi-eye"></i>
                  </button>
                  <button class="btn btn-link" *ngIf="director.status === 'Active'" (click)="markAsResigned(i)" title="Mark as Resigned">
                    <i class="bi bi-person-dash"></i>
                  </button>
                  <button class="btn btn-link text-danger" (click)="removeDirector(i)" title="Remove">
                    <i class="bi bi-trash"></i>
                  </button>
                </div>
              </td>
            </tr>
            <tr *ngIf="getFilteredDirectors().length === 0">
              <td colspan="7" class="text-center py-4">
                <div class="text-muted">No directors found</div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Recent Activities -->
    <div class="card">
      <div class="card-header">
        <h5 class="mb-0">Recent Activities</h5>
      </div>
      <div class="activity-list">
        <div class="activity-item" *ngFor="let activity of recentActivities">
          <div class="activity-icon" [class]="activity.type">
            <i [class]="getActivityIcon(activity.type)"></i>
          </div>
          <div class="activity-content">
            <div class="activity-description">{{ activity.description }}</div>
            <div class="activity-meta">
              <span class="user">{{ activity.user }}</span>
              <span class="time">{{ activity.time }}</span>
            </div>
          </div>
        </div>
        <div *ngIf="recentActivities.length === 0" class="text-center py-4">
          <div class="text-muted">No recent activities</div>
        </div>
      </div>
    </div>
  </div>
</div>

// app-react/src/components/statutory/sections/directors/Directors.tsx
import React, { useState, useEffect } from 'react';
import DirectorModal from './DirectorModal';
import ResignDirectorModal from './ResignDirectorModal';
import ImportDirectorModal from './ImportDirectorModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaSignOutAlt, FaFileImport, FaUsers, FaUserCheck, FaUserMinus, FaClock, FaTrash, FaFileExport, FaFilePdf, FaFileExcel } from 'react-icons/fa';

interface Director {
  id?: string;
  title: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  nationality: string;
  address: string;
  appointmentDate: string;
  resignationDate?: string;
  directorType: string;
  occupation: string;
  otherDirectorships: string;
  shareholding: string;
  status: 'Active' | 'Resigned';
  company?: {
    name: string;
    legalName: string;
  };
}

interface Activity {
  id: string;
  type: 'appointment' | 'update' | 'resignation' | 'deletion';
  entityType: string;
  entityId: string;
  description: string;
  user: string;
  time: string;
}

const Directors: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [directors, setDirectors] = useState<Director[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Active' | 'Resigned'>('All');
  const { user } = useAuth();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showResignModal, setShowResignModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedDirector, setSelectedDirector] = useState<Director | undefined>(undefined);

  useEffect(() => {
    fetchDirectors();
    fetchRecentActivities();
  }, [statusFilter]); // Refresh when status filter changes

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=director&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchDirectors = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/directors/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setDirectors(response.data);
      } else {
        setDirectors([]);
        console.error('Expected array of directors but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load directors');
      console.error('Error fetching directors:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/directors/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      // Create blob link to download
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `directors.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      
      // Append to html link element page
      document.body.appendChild(link);
      
      // Start download
      link.click();
      
      // Clean up and remove the link
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting directors:', error);
      alert('Failed to export directors. Please try again.');
    }
  };

  const handleAddDirector = () => {
    setSelectedDirector(undefined);
    setShowAddModal(true);
  };

  const handleEditDirector = (director: Director) => {
    setSelectedDirector(director);
    setShowAddModal(true);
  };

  const handleResignDirector = (director: Director) => {
    setSelectedDirector(director);
    setShowResignModal(true);
  };

  const handleDeleteDirector = async (director: Director) => {
    if (window.confirm(`Are you sure you want to delete ${director.firstName} ${director.lastName}? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/directors/${user?.companyId}/${director.id}`);
        fetchDirectors();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting director:', error);
        alert('Failed to delete director. Please try again.');
      }
    }
  };

  const handleConfirmResign = async (resignationDate: string) => {
    try {
      await api.post(`/statutory/directors/${user?.companyId}/${selectedDirector?.id}/resign`, {
        resignationDate
      });
      setShowResignModal(false);
      fetchDirectors();
      fetchRecentActivities();
    } catch (err) {
      setError('Failed to resign director');
      console.error('Error resigning director:', err);
    }
  };

  const handleModalSuccess = () => {
    fetchDirectors();
    fetchRecentActivities();
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <DirectorModal
        show={showAddModal}
        onHide={() => setShowAddModal(false)}
        director={selectedDirector}
        onSuccess={handleModalSuccess}
      />
      {selectedDirector && (
        <ResignDirectorModal
          show={showResignModal}
          onHide={() => setShowResignModal(false)}
          director={selectedDirector}
          onConfirm={handleConfirmResign}
        />
      )}
      {user?.companyId && (
        <ImportDirectorModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Directors & Secretaries</h1>
            <p className="text-muted mb-0">Record and manage company directors, secretaries and their details</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddDirector}>
              <FaPlus className="me-2" /> Add Director
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Directors</div>
                    <h3 className="mb-0">{directors.length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaUsers className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Active Directors</div>
                    <h3 className="mb-0">{directors.filter(d => d.status === 'Active').length}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaUserCheck className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Resigned Directors</div>
                    <h3 className="mb-0">{directors.filter(d => d.status === 'Resigned').length}</h3>
                  </div>
                  <div className="bg-secondary bg-opacity-10 p-3 rounded">
                    <FaUserMinus className="text-secondary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Directors Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Active' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Active')}
                >
                  Active
                </Button>
                <Button
                  variant={statusFilter === 'Resigned' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Resigned')}
                >
                  Resigned
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Appointment Date</th>
                  <th>Status</th>
                  {user?.role === 'super_admin' && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {directors.map((director) => (
                  <tr key={director.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{`${director.title} ${director.firstName} ${director.lastName}`}</div>
                          <div className="text-muted small">{director.occupation}</div>
                        </div>
                      </div>
                    </td>
                    <td>{director.directorType}</td>
                    <td>{new Date(director.appointmentDate).toLocaleDateString('en-IE', {
                      day: '2-digit',
                      month: '2-digit',
                      year: 'numeric'
                    })}</td>
                    <td>
                      <Badge bg={director.status === 'Active' ? 'success' : 'secondary'}>
                        {director.status}
                      </Badge>
                    </td>
                    {user?.role === 'super_admin' && (
                      <td>{director.company?.name || director.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditDirector(director)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      {director.status === 'Active' && (
                        <>
                          <Button
                            variant="link"
                            className="p-0 me-3"
                            onClick={() => handleResignDirector(director)}
                          >
                            <FaSignOutAlt className="text-danger" />
                          </Button>
                          <Button
                            variant="link"
                            className="p-0"
                            onClick={() => handleDeleteDirector(director)}
                          >
                            <FaTrash className="text-danger" />
                          </Button>
                        </>
                      )}
                      {director.status === 'Resigned' && (
                        <Button
                          variant="link"
                          className="p-0"
                          onClick={() => handleDeleteDirector(director)}
                        >
                          <FaTrash className="text-danger" />
                        </Button>
                      )}
                    </td>
                  </tr>
                ))}
                {directors.length === 0 && (
                  <tr>
                    <td colSpan={user?.role === 'super_admin' ? 6 : 5} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaUsers className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Directors Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first director or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Directors
                          </Button>
                          <Button variant="primary" onClick={handleAddDirector}>
                            <FaPlus className="me-2" /> Add Director
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">
                <FaClock className="me-2" />
                Recent Activities
              </h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'appointment' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'update' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'resignation' ? (
                            <FaSignOutAlt className="text-danger" />
                          ) : activity.type === 'deletion' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {new Date(activity.time).toLocaleString('en-IE', {
                            day: '2-digit',
                            month: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default Directors;
