// app-react/src/components/settings/sections/security/ChangePasswordModal.tsx
import React, { useState } from 'react';
import { Modal, Button, Form } from 'react-bootstrap';

interface ChangePasswordModalProps {
  onSave: (currentPassword: string, newPassword: string) => void;
  onClose: () => void;
}

interface FormErrors {
  currentPassword?: string;
  newPassword?: string;
  confirmPassword?: string;
}

const ChangePasswordModal: React.FC<ChangePasswordModalProps> = ({ onSave, onClose }) => {
  const [formData, setFormData] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  });
  const [errors, setErrors] = useState<FormErrors>({});

  const validateForm = () => {
    const newErrors: FormErrors = {};
    const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

    if (!formData.currentPassword) {
      newErrors.currentPassword = 'Current password is required';
    }

    if (!formData.newPassword) {
      newErrors.newPassword = 'New password is required';
    } else if (formData.newPassword.length < 8) {
      newErrors.newPassword = 'Password must be at least 8 characters';
    } else if (!passwordRegex.test(formData.newPassword)) {
      newErrors.newPassword = 'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character';
    }

    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Password confirmation is required';
    } else if (formData.newPassword !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (validateForm()) {
      onSave(formData.currentPassword, formData.newPassword);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error when user starts typing
    if (errors[name as keyof FormErrors]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  return (
    <Modal show={true} onHide={onClose}>
      <Form onSubmit={handleSubmit}>
        <Modal.Header closeButton>
          <Modal.Title>Change Password</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {/* Current Password */}
          <Form.Group className="mb-4" controlId="currentPassword">
            <Form.Label>Current Password</Form.Label>
            <Form.Control
              type="password"
              name="currentPassword"
              value={formData.currentPassword}
              onChange={handleChange}
              isInvalid={!!errors.currentPassword}
            />
            <Form.Control.Feedback type="invalid">
              {errors.currentPassword}
            </Form.Control.Feedback>
          </Form.Group>

          {/* New Password */}
          <Form.Group className="mb-4" controlId="newPassword">
            <Form.Label>New Password</Form.Label>
            <Form.Control
              type="password"
              name="newPassword"
              value={formData.newPassword}
              onChange={handleChange}
              isInvalid={!!errors.newPassword}
            />
            <Form.Control.Feedback type="invalid">
              {errors.newPassword}
            </Form.Control.Feedback>
            <Form.Text className="text-muted">
              Password must be at least 8 characters long and contain at least one uppercase letter, 
              one lowercase letter, one number, and one special character.
            </Form.Text>
          </Form.Group>

          {/* Confirm Password */}
          <Form.Group className="mb-4" controlId="confirmPassword">
            <Form.Label>Confirm Password</Form.Label>
            <Form.Control
              type="password"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleChange}
              isInvalid={!!errors.confirmPassword}
            />
            <Form.Control.Feedback type="invalid">
              {errors.confirmPassword}
            </Form.Control.Feedback>
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="link" onClick={onClose}>
            Cancel
          </Button>
          <Button 
            variant="primary" 
            type="submit"
            disabled={!formData.currentPassword || !formData.newPassword || !formData.confirmPassword}
          >
            Change Password
          </Button>
        </Modal.Footer>
      </Form>
    </Modal>
  );
};

export default ChangePasswordModal;

// app/src/app/components/settings/security/modal/change-password-modal.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgbActiveModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-change-password-modal',
  template: `
    <div class="modal-header">
      <h4 class="modal-title">Change Password</h4>
      <button type="button" class="btn-close" (click)="activeModal.dismiss()"></button>
    </div>
    <form [formGroup]="form" (ngSubmit)="onSubmit()">
      <div class="modal-body">
        <!-- Current Password -->
        <div class="mb-4">
          <div class="form-group">
            <label class="form-label">Current Password</label>
            <input type="password" class="form-control" formControlName="currentPassword">
            <div class="form-text text-danger" *ngIf="form.get('currentPassword')?.touched && form.get('currentPassword')?.errors?.['required']">
              Current password is required
            </div>
          </div>
        </div>

        <!-- New Password -->
        <div class="mb-4">
          <div class="form-group">
            <label class="form-label">New Password</label>
            <input type="password" class="form-control" formControlName="newPassword">
            <div class="form-text text-danger" *ngIf="form.get('newPassword')?.touched && form.get('newPassword')?.errors?.['required']">
              New password is required
            </div>
            <div class="form-text text-danger" *ngIf="form.get('newPassword')?.touched && form.get('newPassword')?.errors?.['minlength']">
              Password must be at least 8 characters
            </div>
            <div class="form-text text-danger" *ngIf="form.get('newPassword')?.touched && form.get('newPassword')?.errors?.['pattern']">
              Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character
            </div>
          </div>
        </div>

        <!-- Confirm Password -->
        <div class="mb-4">
          <div class="form-group">
            <label class="form-label">Confirm Password</label>
            <input type="password" class="form-control" formControlName="confirmPassword">
            <div class="form-text text-danger" *ngIf="form.get('confirmPassword')?.touched && form.get('confirmPassword')?.errors?.['required']">
              Password confirmation is required
            </div>
            <div class="form-text text-danger" *ngIf="form.get('confirmPassword')?.touched && form.errors?.['passwordMismatch']">
              Passwords do not match
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link" (click)="activeModal.dismiss()">Cancel</button>
        <button type="submit" class="btn btn-primary" [disabled]="!form.valid">Change Password</button>
      </div>
    </form>
  `,
  styles: [`
    .form-label {
      font-size: 0.875rem;
      margin-bottom: 0.25rem;
    }
  `],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, NgbModule]
})
export class ChangePasswordModalComponent implements OnInit {
  form!: FormGroup;

  constructor(
    public activeModal: NgbActiveModal,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.form = this.fb.group({
      currentPassword: ['', Validators.required],
      newPassword: ['', [
        Validators.required,
        Validators.minLength(8),
        Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/)
      ]],
      confirmPassword: ['', Validators.required]
    }, { validators: this.passwordMatchValidator });
  }

  passwordMatchValidator(g: FormGroup) {
    return g.get('newPassword')?.value === g.get('confirmPassword')?.value
      ? null
      : { passwordMismatch: true };
  }

  onSubmit(): void {
    if (this.form.valid) {
      const { currentPassword, newPassword } = this.form.value;
      this.activeModal.close({ currentPassword, newPassword });
    }
  }
}
