// app/src/components/shared/TinySidebar.tsx
import React from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

type SectionType = 'statutory' | 'compliance' | 'tax' | 'crm' | 'settings' | 'help';

interface Section {
  id: SectionType;
  title: string;
  icon: string;
  route: string;
}

interface TinySidebarProps {
  isDarkMode: boolean;
  notificationCount: number;
  userAvatar: string;
  userName: string;
  activeSection: SectionType;
  onSectionChange: (section: SectionType) => void;
  onThemeToggle: () => void;
  onNotificationsToggle: () => void;
  onUserMenuToggle: () => void;
}

const TinySidebar: React.FC<TinySidebarProps> = ({
  isDarkMode,
  notificationCount,
  userAvatar,
  userName,
  activeSection,
  onSectionChange,
  onThemeToggle,
  onNotificationsToggle,
  onUserMenuToggle
}) => {
  const navigate = useNavigate();
  const location = useLocation();
  const { user, logout } = useAuth();

  const topSections: Section[] = [
    { id: 'statutory', title: 'Statutory', icon: 'bi bi-journal-bookmark', route: '/statutory/dashboard' },
    { id: 'compliance', title: 'Compliance', icon: 'bi bi-shield-check', route: '/compliance/dashboard' },
    { id: 'tax', title: 'Tax', icon: 'bi bi-calculator', route: '/tax/dashboard' },
    { id: 'crm', title: 'CRM', icon: 'bi bi-people', route: '/crm/contacts' }
  ];

  const bottomSections: Section[] = [
    { id: 'settings', title: 'Settings', icon: 'bi bi-gear', route: '/settings' },
    { id: 'help', title: 'Help', icon: 'bi bi-question-circle', route: '/help' }
  ];

  const navigateToUserDashboard = () => {
    if (user?.roles?.[0]) {
      navigate(`/dashboard/${user.roles[0].toLowerCase()}`);
    }
  };

  const selectSection = (section: SectionType) => {
    onSectionChange(section);
    
    switch(section) {
      case 'statutory':
      case 'compliance':
      case 'tax':
        navigate(`/${section}/dashboard`);
        break;
      case 'settings':
      case 'help':
        navigate(`/${section}`);
        break;
      case 'crm':
        navigate('/crm/contacts');
        break;
    }
  };

  const handleLogout = () => {
    logout();
  };

  return (
    <aside className="position-fixed start-0 top-0 bottom-0 bg-light border-end" style={{ width: '48px', zIndex: 1030 }}>
      <div className="d-flex flex-column h-100">
        <div className="p-2">
          <ul className="nav flex-column align-items-center m-0 p-0">
            <li className="nav-item mb-1">
              <button
                className="nav-link d-flex justify-content-center align-items-center rounded p-2"
                style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                onClick={navigateToUserDashboard}
                title="Home"
              >
                <i className="bi bi-house fs-5"></i>
              </button>
            </li>
            {topSections.map((section) => (
              <li className="nav-item mb-1" key={section.id}>
                <button
                  className={`nav-link d-flex justify-content-center align-items-center rounded p-2 ${
                    activeSection === section.id ? 'active' : ''
                  }`}
                  style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                  onClick={() => selectSection(section.id)}
                  title={section.title}
                >
                  <i className={`${section.icon} fs-5`}></i>
                </button>
              </li>
            ))}
          </ul>
        </div>

        <div className="mt-auto p-2">
          <ul className="nav flex-column align-items-center m-0 p-0">
            <li className="nav-item mb-1">
              <button
                className="nav-link d-flex justify-content-center align-items-center rounded p-2"
                style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                onClick={onThemeToggle}
                title="Toggle Theme"
              >
                <i className={`bi fs-5 ${isDarkMode ? 'bi-sun-fill' : 'bi-moon-fill'}`}></i>
              </button>
            </li>
            <li className="nav-item mb-1 position-relative">
              <button
                className="nav-link d-flex justify-content-center align-items-center rounded p-2"
                style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                onClick={onNotificationsToggle}
                title="Notifications"
              >
                <i className="bi bi-bell fs-5"></i>
                {notificationCount > 0 && (
                  <span className="position-absolute top-0 end-0 translate-middle badge rounded-pill bg-danger">
                    {notificationCount}
                  </span>
                )}
              </button>
            </li>
            <li className="nav-item mb-1">
              <button
                className="nav-link d-flex justify-content-center align-items-center rounded p-2"
                style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                onClick={onUserMenuToggle}
                title="Profile"
              >
                <i className={`${userAvatar || 'bi bi-person-circle'} fs-5`}></i>
              </button>
            </li>
            {bottomSections.map((section) => (
              <li className="nav-item mb-1" key={section.id}>
                <button
                  className={`nav-link d-flex justify-content-center align-items-center rounded p-2 ${
                    activeSection === section.id ? 'active' : ''
                  }`}
                  style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                  onClick={() => selectSection(section.id)}
                  title={section.title}
                >
                  <i className={`${section.icon} fs-5`}></i>
                </button>
              </li>
            ))}
            <li className="nav-item">
              <button
                className="nav-link d-flex justify-content-center align-items-center rounded p-2"
                style={{ width: '40px', height: '40px', border: 'none', background: 'none' }}
                onClick={handleLogout}
                title="Logout"
              >
                <i className="bi bi-box-arrow-right fs-5"></i>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </aside>
  );
};

export default TinySidebar;

// app/src/app/components/tiny-sidebar/tiny-sidebar.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth/auth.service';

type SectionType = 'statutory' | 'compliance' | 'tax' | 'settings' | 'help';

interface Section {
  id: SectionType;
  title: string;
  icon: string;
  route: string;
}

@Component({
  selector: 'app-tiny-sidebar',
  template: `
    <!-- Tiny Nav Panel -->
    <aside class="position-fixed start-0 top-0 bottom-0 bg-light border-end" style="width: 48px;">
      <!-- Top Section -->
      <div class="d-flex flex-column h-100">
        <div class="p-2">
          <ul class="nav flex-column align-items-center m-0 p-0">
            <!-- Home Button -->
            <li class="nav-item mb-1">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2" 
                 style="width: 40px; height: 40px;"
                 (click)="navigateToUserDashboard()"
                 title="Home">
                <i class="bi bi-house fs-5"></i>
              </a>
            </li>
            <li class="nav-item mb-1" *ngFor="let section of topSections">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2" 
                 style="width: 40px; height: 40px;"
                 [class.active]="activeSection === section.id"
                 (click)="selectSection(section.id)"
                 [routerLink]="[section.route]"
                 routerLinkActive="active"
                 [title]="section.title">
                <i [class]="section.icon + ' fs-5'"></i>
              </a>
            </li>
          </ul>
        </div>

        <!-- Bottom Section -->
        <div class="mt-auto p-2">
          <ul class="nav flex-column align-items-center m-0 p-0">
            <li class="nav-item mb-1">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2"
                 style="width: 40px; height: 40px;"
                 (click)="toggleTheme()"
                 title="Toggle Theme">
                <i class="bi fs-5" [class.bi-moon-fill]="!isDarkMode" [class.bi-sun-fill]="isDarkMode"></i>
              </a>
            </li>
            <li class="nav-item mb-1 position-relative">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2"
                 style="width: 40px; height: 40px;"
                 (click)="toggleNotifications()"
                 title="Notifications">
                <i class="bi bi-bell fs-5"></i>
                <span class="position-absolute top-0 end-0 translate-middle badge rounded-pill bg-danger" *ngIf="notificationCount > 0">
                  {{ notificationCount }}
                </span>
              </a>
            </li>
            <li class="nav-item mb-1">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2"
                 style="width: 40px; height: 40px;"
                 (click)="toggleUserMenu()"
                 title="Profile">
                <i [class]="userAvatar + ' fs-5'"></i>
              </a>
            </li>
            <li class="nav-item mb-1" *ngFor="let section of bottomSections">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2"
                 style="width: 40px; height: 40px;"
                 [class.active]="activeSection === section.id"
                 (click)="selectSection(section.id)"
                 [routerLink]="[section.route]"
                 routerLinkActive="active"
                 [title]="section.title">
                <i [class]="section.icon + ' fs-5'"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex justify-content-center align-items-center rounded p-2"
                 style="width: 40px; height: 40px;"
                 (click)="onLogout()"
                 title="Logout">
                <i class="bi bi-box-arrow-right fs-5"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </aside>
  `,
  styles: [`
    :host {
      display: block;
      z-index: 1030;
    }

    .nav-link {
      color: var(--bs-secondary);
      transition: all 0.2s;
    }

    .nav-link:hover,
    .nav-link.active {
      color: var(--bs-primary);
      background-color: rgba(var(--bs-primary-rgb), 0.1);
    }

    @media (max-width: 768px) {
      .nav-link {
        width: 32px !important;
        height: 32px !important;
      }
      .nav-link i {
        font-size: 1rem !important;
      }
    }
  `],
  standalone: true,
  imports: [CommonModule, RouterModule]
})
export class TinySidebarComponent implements OnInit {
  @Input() isDarkMode = false;
  @Input() notificationCount = 0;
  @Input() userAvatar = '';
  @Input() userName = '';
  @Input() activeSection: SectionType = 'statutory';

  @Output() sectionChange = new EventEmitter<SectionType>();
  @Output() themeToggle = new EventEmitter<void>();
  @Output() notificationsToggle = new EventEmitter<void>();
  @Output() userMenuToggle = new EventEmitter<void>();
  @Output() logout = new EventEmitter<void>();

  topSections: Section[] = [
    { id: 'statutory', title: 'Statutory', icon: 'bi bi-journal-bookmark', route: '/statutory/dashboard' },
    { id: 'compliance', title: 'Compliance', icon: 'bi bi-shield-check', route: '/compliance/dashboard' },
    { id: 'tax', title: 'Tax', icon: 'bi bi-calculator', route: '/tax/dashboard' }
  ];

  bottomSections: Section[] = [
    { id: 'settings', title: 'Settings', icon: 'bi bi-gear', route: '/settings' },
    { id: 'help', title: 'Help', icon: 'bi bi-question-circle', route: '/help' }
  ];

  constructor(
    private router: Router,
    private authService: AuthService
  ) {}

  ngOnInit() {}

  navigateToUserDashboard() {
    const userRole = this.authService.getUserRole();
    if (userRole) {
      this.router.navigate([`/dashboard/${userRole}`]);
    }
  }

  selectSection(section: SectionType) {
    this.sectionChange.emit(section);
    
    // Navigate to the main dashboard of each module
    switch(section) {
      case 'statutory':
      case 'compliance':
      case 'tax':
        this.router.navigate([`/${section}/dashboard`]);
        break;
      case 'settings':
      case 'help':
        this.router.navigate([`/${section}`]);
        break;
    }
  }

  toggleTheme() {
    this.themeToggle.emit();
  }

  toggleNotifications() {
    this.notificationsToggle.emit();
  }

  toggleUserMenu() {
    this.userMenuToggle.emit();
  }

  onLogout() {
    this.logout.emit();
  }
}

<!-- Tiny Nav Panel -->
<div class="tiny-nav">
  <div class="top-section">
    <ul class="nav-items">
      <li>
        <a (click)="selectSection('books')"
           [routerLink]="['/books/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'books'">
          <i class="bi bi-journal-text"></i>
          <span class="tooltip">Books</span>
        </a>
      </li>
      <li>
        <a (click)="selectSection('crm')"
           [routerLink]="['/crm/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'crm'">
          <i class="bi bi-people"></i>
          <span class="tooltip">CRM</span>
        </a>
      </li>
      <li>
        <a (click)="selectSection('compliance')"
           [routerLink]="['/compliance/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'compliance'">
          <i class="bi bi-shield-check"></i>
          <span class="tooltip">Compliance</span>
        </a>
      </li>
      <li>
        <a (click)="selectSection('carbon')"
           [routerLink]="['/carbon/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'carbon'">
          <i class="bi bi-cloud"></i>
          <span class="tooltip">Carbon</span>
        </a>
      </li>
      <li>
        <a (click)="selectSection('tax')"
           [routerLink]="['/tax/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'tax'">
          <i class="bi bi-calculator"></i>
          <span class="tooltip">Tax</span>
        </a>
      </li>
      <li>
        <a (click)="selectSection('statutory')"
           [routerLink]="['/statutory/dashboard']"
           routerLinkActive="active"
           [class.active]="activeSection === 'statutory'">
          <i class="bi bi-journal-bookmark"></i>
          <span class="tooltip">Statutory</span>
        </a>
      </li>
    </ul>
  </div>

  <div class="bottom-section">
    <ul class="nav-items">
      <!-- Theme Toggle -->
      <li>
        <a (click)="toggleTheme()">
          <i class="bi" [class.bi-moon-fill]="!isDarkMode" [class.bi-sun-fill]="isDarkMode"></i>
          <span class="tooltip">Toggle Theme</span>
        </a>
      </li>
      <!-- Notifications -->
      <li>
        <a (click)="toggleNotifications()">
          <i class="bi bi-bell"></i>
          <span class="notification-badge" *ngIf="notificationCount > 0">
            {{ notificationCount }}
          </span>
          <span class="tooltip">Notifications</span>
        </a>
      </li>
      <!-- User Menu -->
      <li>
        <a (click)="toggleUserMenu()">
          <i [class]="userAvatar" class="user-avatar"></i>
          <span class="tooltip">Profile</span>
        </a>
      </li>
      <!-- Settings -->
      <li>
        <a (click)="selectSection('settings')"
           [routerLink]="['/settings']"
           routerLinkActive="active"
           [class.active]="activeSection === 'settings'">
          <i class="bi bi-gear"></i>
          <span class="tooltip">Settings</span>
        </a>
      </li>
      <!-- Help -->
      <li>
        <a (click)="selectSection('help')"
           [routerLink]="['/help']"
           routerLinkActive="active"
           [class.active]="activeSection === 'help'">
          <i class="bi bi-question-circle"></i>
          <span class="tooltip">Help</span>
        </a>
      </li>
    </ul>
  </div>
</div>
