// app/src/components/statutory/sections/shares/Shares.tsx
import React, { useState, useEffect } from 'react';
import ShareModal from './ShareModal';
import ImportShareModal from './ImportShareModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaClock, FaTrash, FaFileExport, FaFilePdf, FaFileExcel, FaCoins, FaCheckCircle, FaArchive, FaFileImport } from 'react-icons/fa';

import { Share, Activity } from '../../../../services/statutory/types';
import { formatDDMMYYYY } from '@bradan/shared';

const Shares: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [shares, setShares] = useState<Share[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Active' | 'Inactive' | 'Archived'>('All');
  const { user } = useAuth();

  const [showModal, setShowModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedShare, setSelectedShare] = useState<Share | undefined>(undefined);

  useEffect(() => {
    fetchShares();
    fetchRecentActivities();
  }, [statusFilter]);

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=share&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchShares = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/shares/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setShares(response.data);
      } else {
        setShares([]);
        console.error('Expected array of shares but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load share classes');
      console.error('Error fetching shares:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/shares/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `shares.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting shares:', error);
      alert('Failed to export shares. Please try again.');
    }
  };

  const handleAddShare = () => {
    setSelectedShare(undefined);
    setShowModal(true);
  };

  const handleEditShare = (share: Share) => {
    setSelectedShare(share);
    setShowModal(true);
  };

  const handleDeleteShare = async (share: Share) => {
    if (window.confirm(`Are you sure you want to delete the ${share.class} share class? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/shares/${user?.companyId}/${share.id}`);
        fetchShares();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting share:', error);
        alert('Failed to delete share class. Please try again.');
      }
    }
  };

  const handleModalSuccess = () => {
    fetchShares();
    fetchRecentActivities();
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <ShareModal
        show={showModal}
        onHide={() => setShowModal(false)}
        share={selectedShare}
        onSuccess={handleModalSuccess}
      />
      {user?.companyId && (
        <ImportShareModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Shares Register</h1>
            <p className="text-muted mb-0">Record and manage company share classes and their details</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddShare}>
              <FaPlus className="me-2" /> Add Share Class
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Share Classes</div>
                    <h3 className="mb-0">{shares.length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaCoins className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Active Share Classes</div>
                    <h3 className="mb-0">{shares.filter(s => s.status === 'Active').length}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaCheckCircle className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Archived Share Classes</div>
                    <h3 className="mb-0">{shares.filter(s => s.status === 'Archived').length}</h3>
                  </div>
                  <div className="bg-secondary bg-opacity-10 p-3 rounded">
                    <FaArchive className="text-secondary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Shares Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Active' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Active')}
                >
                  Active
                </Button>
                <Button
                  variant={statusFilter === 'Inactive' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Inactive')}
                >
                  Inactive
                </Button>
                <Button
                  variant={statusFilter === 'Archived' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Archived')}
                >
                  Archived
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Share Class</th>
                  <th>Type</th>
                  <th>Nominal Value</th>
                  <th>Total Issued</th>
                  <th>Rights</th>
                  <th>Status</th>
                  {user?.roles?.includes('super_admin') && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {shares.map((share) => (
                  <tr key={share.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{share.class}</div>
                          <div className="text-muted small">{share.description}</div>
                        </div>
                      </div>
                    </td>
                    <td>{share.type}</td>
                    <td>{`${share.nominalValue} ${share.currency}`}</td>
                    <td>{share.totalIssued.toLocaleString()}</td>
                    <td>
                      <div className="small">
                        {share.votingRights && <Badge bg="info" className="me-1">Voting</Badge>}
                        {share.dividendRights && <Badge bg="info" className="me-1">Dividend</Badge>}
                        {share.transferable && <Badge bg="info">Transferable</Badge>}
                      </div>
                    </td>
                    <td>
                      <Badge bg={
                        share.status === 'Active' ? 'success' :
                        share.status === 'Inactive' ? 'warning' :
                        'secondary'
                      }>
                        {share.status}
                      </Badge>
                    </td>
                    {user?.roles?.includes('super_admin') && (
                      <td>{share.company?.name || share.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditShare(share)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      <Button
                        variant="link"
                        className="p-0"
                        onClick={() => handleDeleteShare(share)}
                      >
                        <FaTrash className="text-danger" />
                      </Button>
                    </td>
                  </tr>
                ))}
                {shares.length === 0 && (
                  <tr>
                    <td colSpan={user?.roles?.includes('super_admin') ? 8 : 7} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaCoins className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Share Classes Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first share class or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Share Classes
                          </Button>
                          <Button variant="primary" onClick={handleAddShare}>
                            <FaPlus className="me-2" /> Add Share Class
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">
                <FaClock className="me-2" />
                Recent Activities
              </h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'added' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'updated' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'status_changed' ? (
                            <FaEdit className="text-warning" />
                          ) : activity.type === 'removed' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {formatDDMMYYYY(new Date(activity.time))}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default Shares;

// app/src/app/components/statutory/shares/shares.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, of } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, map } from 'rxjs/operators';

import { CreateShareModalComponent } from './modal/create-share-modal.component';
import { EditShareModalComponent } from './modal/edit-share-modal.component';
import { ViewShareModalComponent } from './modal/view-share-modal.component';
import { ConfirmModalComponent } from './modal/confirm-modal.component';

import { ShareService } from '../../../services/statutory/share.service';
import { CompanyService } from '../../../services/settings/company.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { AuthService } from '../../../services/auth/auth.service';

import { Share, Activity, ActivityResponse } from '../statutory.types';

@Component({
  selector: 'app-shares',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateShareModalComponent,
    EditShareModalComponent,
    ViewShareModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Header -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 class="h3 mb-2">Share Register</h1>
          <p class="text-muted mb-0">Manage and track company share classes and their details</p>
        </div>
        <div>
          <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddShareModal()">
            <i class="bi bi-plus-lg"></i>
            <span>Add Share Class</span>
          </button>
        </div>
      </div>

      <!-- Metrics -->
      <div class="row g-3 mb-4">
        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Share Classes</span>
                <i class="bi bi-diagram-3 fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getActiveShareClasses().length }}</h3>
              <small class="text-muted">Active share classes</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Total Shares</span>
                <i class="bi bi-pie-chart fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getTotalShares() }}</h3>
              <small class="text-muted">Total shares issued</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Share Value</span>
                <i class="bi bi-currency-pound fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getTotalValue() }}</h3>
              <small class="text-muted">Total nominal value</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Voting Shares</span>
                <i class="bi bi-check-circle fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getVotingShares() }}</h3>
              <small class="text-muted">Shares with voting rights</small>
            </div>
          </div>
        </div>
      </div>

      <!-- Share Classes Table -->
      <div class="card mb-4">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Share Classes</h5>
          <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAll()">
            <i [class]="showAll ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
            <span>{{ showAll ? 'Show Active Only' : 'Show All Classes' }}</span>
          </button>
        </div>
        <div class="table-responsive">
          <table class="table table-hover mb-0">
            <thead class="bg-light">
              <tr>
                <th class="text-uppercase small fw-semibold text-secondary">Class</th>
                <th class="text-uppercase small fw-semibold text-secondary">Type</th>
                <th class="text-uppercase small fw-semibold text-secondary">Nominal Value</th>
                <th class="text-uppercase small fw-semibold text-secondary">Total Issued</th>
                <th class="text-uppercase small fw-semibold text-secondary">Rights</th>
                <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let share of getFilteredShares()">
                <td>
                  <div class="d-flex align-items-center gap-2">
                    <i class="bi bi-diagram-3 text-secondary"></i>
                    <a href="#" class="text-decoration-none" (click)="viewShare(share, $event)">
                      {{ share.class }}
                    </a>
                  </div>
                </td>
                <td>{{ share.type }}</td>
                <td>{{ share.nominalValue }} {{ share.currency }}</td>
                <td>{{ share.totalIssued }}</td>
                <td>
                  <div class="d-flex gap-2">
                    <span class="badge" [class.text-bg-success]="share.votingRights" [class.text-bg-secondary]="!share.votingRights">
                      <i class="bi" [class.bi-check-lg]="share.votingRights" [class.bi-x-lg]="!share.votingRights"></i>
                      Voting
                    </span>
                    <span class="badge" [class.text-bg-success]="share.dividendRights" [class.text-bg-secondary]="!share.dividendRights">
                      <i class="bi" [class.bi-check-lg]="share.dividendRights" [class.bi-x-lg]="!share.dividendRights"></i>
                      Dividend
                    </span>
                  </div>
                </td>
                <td>
                  <span [class]="'badge ' + (share.status === 'Active' ? 'text-bg-success' : 'text-bg-secondary')">
                    {{ share.status }}
                  </span>
                </td>
                <td>
                  <div class="btn-group">
                    <button class="btn btn-link btn-sm text-body px-2" (click)="viewShare(share)" title="View Details">
                      <i class="bi bi-eye"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-body px-2" (click)="editShare(share)" title="Edit">
                      <i class="bi bi-pencil"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-danger px-2" (click)="removeShare(share)" title="Remove">
                      <i class="bi bi-trash"></i>
                    </button>
                  </div>
                </td>
              </tr>
              <tr *ngIf="getFilteredShares().length === 0">
                <td colspan="7" class="text-center py-4 text-muted">
                  <i class="bi bi-info-circle me-2"></i>
                  No share classes found
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Recent Activities -->
      <div class="card">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Recent Activities</h5>
          <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
            <i class="bi bi-arrow-clockwise me-1"></i>
            <span>Refresh</span>
          </button>
        </div>
        <div class="card-body">
          <div class="list-group list-group-flush">
            <div class="list-group-item px-0" *ngFor="let activity of recentActivities">
              <div class="d-flex align-items-start gap-3">
                <div class="bg-light rounded p-2">
                  <i [class]="getActivityIcon(activity.type)"></i>
                </div>
                <div>
                  <p class="mb-1">{{ activity.description }}</p>
                  <div class="d-flex align-items-center gap-2 small">
                    <span class="text-primary">{{ activity.user }}</span>
                    <span class="text-muted">{{ activity.time }}</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
              <i class="bi bi-info-circle me-2"></i>
              No recent activities
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class SharesComponent implements OnInit, OnDestroy {
  shares: Share[] = [];
  showAll = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private shareService: ShareService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's shares
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.shareService.getShares(companyId, this.showAll ? undefined : 'Active').pipe(
          map(shares => shares.map(s => ({ ...s, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading shares:', error);
        this.error = 'Failed to load shares. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(sharesArrays => {
      this.shares = sharesArrays.flat();
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'share',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  openAddShareModal(): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(CreateShareModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.result.then(
      (newShare: Share) => {
        this.shareService.createShare(companyId, newShare)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create share class. Please try again.';
              console.error('Error creating share class:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(share => {
              if (share) {
                return this.addActivity(companyId, {
                  type: 'added',
                  entityType: 'share',
                  entityId: share.id,
                  description: `${share.class} share class added with ${share.totalIssued} shares`,
                  user: 'System'
                }).pipe(map(() => share));
              }
              return of(null);
            })
          )
          .subscribe(share => {
            if (share) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  viewShare(share: Share, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewShareModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.share = {...share};
    
    modalRef.result.then(
      (result: { action: string; share: Share } | undefined) => {
        if (result?.action === 'edit') {
          this.editShare(result.share);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editShare(share: Share): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(EditShareModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.share = {...share};
    
    modalRef.result.then(
      (updatedShare: Share) => {
        this.shareService.updateShare(companyId, share.id, updatedShare)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update share class. Please try again.';
              console.error('Error updating share class:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                return this.addActivity(companyId, {
                  type: 'updated',
                  entityType: 'share',
                  entityId: share.id,
                  description: `${share.class} share class details updated`,
                  user: 'System'
                }).pipe(map(() => result));
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeShare(share: Share): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove ${share.class} share class?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.shareService.deleteShare(companyId, share.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove share class. Please try again.';
                console.error('Error removing share class:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                return this.addActivity(companyId, {
                  type: 'removed',
                  entityType: 'share',
                  entityId: share.id,
                  description: `${share.class} share class removed`,
                  user: 'System'
                });
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  toggleShowAll(): void {
    this.showAll = !this.showAll;
    this.refreshData();
  }

  getFilteredShares(): Share[] {
    return this.showAll 
      ? this.shares 
      : this.shares.filter(s => s.status === 'Active');
  }

  getActiveShareClasses(): Share[] {
    return this.shares.filter(s => s.status === 'Active');
  }

  getTotalShares(): number {
    return this.shares.reduce((sum, s) => sum + s.totalIssued, 0);
  }

  getTotalValue(): string {
    const gbpShares = this.shares.filter(s => s.currency === 'GBP');
    const eurShares = this.shares.filter(s => s.currency === 'EUR');
    const usdShares = this.shares.filter(s => s.currency === 'USD');

    const gbpTotal = gbpShares.reduce((sum, s) => sum + (s.nominalValue * s.totalIssued), 0);
    const eurTotal = eurShares.reduce((sum, s) => sum + (s.nominalValue * s.totalIssued), 0);
    const usdTotal = usdShares.reduce((sum, s) => sum + (s.nominalValue * s.totalIssued), 0);

    const parts = [];
    if (gbpTotal > 0) parts.push(`£${gbpTotal}`);
    if (eurTotal > 0) parts.push(`€${eurTotal}`);
    if (usdTotal > 0) parts.push(`$${usdTotal}`);

    return parts.join(' + ') || '£0';
  }

  getVotingShares(): number {
    return this.shares
      .filter(s => s.status === 'Active' && s.votingRights)
      .reduce((sum, s) => sum + s.totalIssued, 0);
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'added':
        return 'bi bi-plus-circle';
      case 'updated':
        return 'bi bi-pencil';
      case 'removed':
        return 'bi bi-trash';
      case 'status_changed':
        return 'bi bi-arrow-repeat';
      default:
        return 'bi bi-activity';
    }
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }
}

<div class="container-fluid p-4">
  <div class="row mb-4">
    <div class="col">
      <h1 class="mb-0">Share Register</h1>
      <p class="text-muted">Manage share classes and record share transfers</p>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Add Share Class</h5>
          <form [formGroup]="shareClassForm" (ngSubmit)="onShareClassSubmit()">
            <div class="mb-3">
              <label class="form-label">Share Class Name</label>
              <input type="text" class="form-control" formControlName="name" placeholder="e.g., Ordinary">
            </div>

            <div class="mb-3">
              <label class="form-label">Nominal Value (£)</label>
              <input type="number" class="form-control" formControlName="nominalValue" step="0.01">
            </div>

            <div class="mb-3">
              <label class="form-label">Total Shares</label>
              <input type="number" class="form-control" formControlName="totalShares">
            </div>

            <div class="mb-3">
              <div class="form-check">
                <input type="checkbox" class="form-check-input" formControlName="votingRights" id="votingRights">
                <label class="form-check-label" for="votingRights">Voting Rights</label>
              </div>
            </div>

            <div class="mb-3">
              <div class="form-check">
                <input type="checkbox" class="form-check-input" formControlName="dividendRights" id="dividendRights">
                <label class="form-check-label" for="dividendRights">Dividend Rights</label>
              </div>
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="!shareClassForm.valid">
              Add Share Class
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center mb-4">
            <h5 class="card-title mb-0">Share Classes</h5>
            <div class="total-capital">
              Total Share Capital: <strong>{{ formatCurrency(calculateTotalShareCapital()) }}</strong>
            </div>
          </div>
          
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Share Class</th>
                  <th>Nominal Value</th>
                  <th>Total Shares</th>
                  <th>Share Capital</th>
                  <th>Rights</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let shareClass of shareClasses; let i = index">
                  <td>{{ shareClass.name }}</td>
                  <td>{{ formatCurrency(shareClass.nominalValue) }}</td>
                  <td>{{ shareClass.totalShares }}</td>
                  <td>{{ formatCurrency(shareClass.nominalValue * shareClass.totalShares) }}</td>
                  <td>
                    <span class="badge bg-primary me-1" *ngIf="shareClass.votingRights">Voting</span>
                    <span class="badge bg-success" *ngIf="shareClass.dividendRights">Dividend</span>
                  </td>
                  <td>
                    <button class="btn btn-sm btn-outline-danger" (click)="removeShareClass(i)">
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
                <tr *ngIf="shareClasses.length === 0">
                  <td colspan="6" class="text-center py-4 text-muted">
                    No share classes added yet
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Record Share Transfer</h5>
          <form [formGroup]="transferForm" (ngSubmit)="onTransferSubmit()">
            <div class="mb-3">
              <label class="form-label">Date</label>
              <input type="date" class="form-control" formControlName="date">
            </div>

            <div class="mb-3">
              <label class="form-label">Share Class</label>
              <select class="form-select" formControlName="shareClass">
                <option value="">Select share class</option>
                <option [value]="shareClass.name" *ngFor="let shareClass of shareClasses">
                  {{ shareClass.name }}
                </option>
              </select>
            </div>

            <div class="mb-3">
              <label class="form-label">Transferor</label>
              <input type="text" class="form-control" formControlName="transferor">
            </div>

            <div class="mb-3">
              <label class="form-label">Transferee</label>
              <input type="text" class="form-control" formControlName="transferee">
            </div>

            <div class="mb-3">
              <label class="form-label">Number of Shares</label>
              <input type="number" class="form-control" formControlName="numberOfShares">
            </div>

            <div class="mb-3">
              <label class="form-label">Consideration (£)</label>
              <input type="number" class="form-control" formControlName="consideration" step="0.01">
            </div>

            <div class="mb-3">
              <label class="form-label">Certificate Number</label>
              <input type="text" class="form-control" formControlName="certificateNumber">
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="!transferForm.valid">
              Record Transfer
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Transfer History</h5>
          
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Share Class</th>
                  <th>From</th>
                  <th>To</th>
                  <th>Shares</th>
                  <th>Consideration</th>
                  <th>Certificate</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let transfer of transfers; let i = index">
                  <td>{{ transfer.date | date }}</td>
                  <td>{{ transfer.shareClass }}</td>
                  <td>{{ transfer.transferor }}</td>
                  <td>{{ transfer.transferee }}</td>
                  <td>{{ transfer.numberOfShares }}</td>
                  <td>{{ formatCurrency(transfer.consideration) }}</td>
                  <td>{{ transfer.certificateNumber }}</td>
                  <td>
                    <button class="btn btn-sm btn-outline-danger" (click)="removeTransfer(i)">
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
                <tr *ngIf="transfers.length === 0">
                  <td colspan="8" class="text-center py-4 text-muted">
                    No transfers recorded yet
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
