// app/src/app/components/statutory/meetings/meetings.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, of } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, map } from 'rxjs/operators';

import { CreateMeetingModalComponent } from './modal/create-meeting-modal.component';
import { EditMeetingModalComponent } from './modal/edit-meeting-modal.component';
import { ViewMeetingModalComponent } from './modal/view-meeting-modal.component';
import { ConfirmModalComponent } from './modal/confirm-modal.component';

import { MeetingService } from '../../../services/statutory/meeting.service';
import { CompanyService } from '../../../services/settings/company.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { AuthService } from '../../../services/auth/auth.service';

import { Meeting, Activity, DocumentStatus, ActivityResponse } from '../statutory.types';

@Component({
  selector: 'app-meetings',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateMeetingModalComponent,
    EditMeetingModalComponent,
    ViewMeetingModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Header -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 class="h3 mb-2">General Meetings Minutes</h1>
          <p class="text-muted mb-0">Record and manage company general meetings and resolutions</p>
        </div>
        <div>
          <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddMeetingModal()">
            <i class="bi bi-plus-lg"></i>
            <span>Add Meeting</span>
          </button>
        </div>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading" class="text-center py-5">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>

      <!-- Error State -->
      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <!-- Content -->
      <ng-container *ngIf="!loading && !error">
        <!-- Metrics -->
        <div class="row g-3 mb-4">
          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Total Meetings</span>
                  <i class="bi bi-calendar-event fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ meetings.length }}</h3>
                <small class="text-muted">Recorded meetings</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Resolutions</span>
                  <i class="bi bi-file-text fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getTotalResolutions() }}</h3>
                <small class="text-muted">Total resolutions</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Passed</span>
                  <i class="bi bi-check-circle fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getPassedResolutionsPercentage() }}%</h3>
                <small class="text-muted">Resolution success rate</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Quorum</span>
                  <i class="bi bi-people fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getQuorumAchievedPercentage() }}%</h3>
                <small class="text-muted">Quorum achievement rate</small>
              </div>
            </div>
          </div>
        </div>

        <!-- Meetings Table -->
        <div class="card mb-4">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Meetings</h5>
            <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAll()">
              <i [class]="showAll ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
              <span>{{ showAll ? 'Show Recent Only' : 'Show All Meetings' }}</span>
            </button>
          </div>
          <div class="table-responsive">
            <table class="table table-hover mb-0">
              <thead class="bg-light">
                <tr>
                  <th class="text-uppercase small fw-semibold text-secondary">ID</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Type</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Date</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Chairperson</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Quorum</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let meeting of getFilteredMeetings()">
                  <td>
                    <div class="d-flex align-items-center gap-2">
                      <i class="bi bi-calendar-event text-secondary"></i>
                      <a href="#" class="text-decoration-none" (click)="viewMeeting(meeting, $event)">
                        {{ meeting.id }}
                      </a>
                    </div>
                  </td>
                  <td>{{ meeting.meetingType }}</td>
                  <td>{{ formatDate(meeting.meetingDate) }}</td>
                  <td>{{ meeting.chairperson }}</td>
                  <td>
                    <span [class]="'badge ' + (meeting.quorum?.achieved ? 'text-bg-success' : 'text-bg-danger')">
                      {{ meeting.quorum?.present || 0 }}/{{ meeting.quorum?.required || 0 }}
                    </span>
                  </td>
                  <td>
                    <span [class]="'badge ' + getStatusClass(meeting.status)">
                      {{ meeting.status }}
                    </span>
                  </td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-link btn-sm text-body px-2" (click)="viewMeeting(meeting)" title="View Details">
                        <i class="bi bi-eye"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-body px-2" (click)="editMeeting(meeting)" title="Edit">
                        <i class="bi bi-pencil"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-danger px-2" (click)="removeMeeting(meeting)" title="Remove">
                        <i class="bi bi-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                <tr *ngIf="getFilteredMeetings().length === 0">
                  <td colspan="7" class="text-center py-4 text-muted">
                    <i class="bi bi-info-circle me-2"></i>
                    No meetings found
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Recent Activities -->
        <div class="card">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Recent Activities</h5>
            <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
              <i class="bi bi-arrow-clockwise me-1"></i>
              <span>Refresh</span>
            </button>
          </div>
          <div class="card-body">
            <div class="list-group list-group-flush">
              <div class="list-group-item px-0" *ngFor="let activity of recentActivities">
                <div class="d-flex align-items-start gap-3">
                  <div class="bg-light rounded p-2">
                    <i [class]="getActivityIcon(activity.type)"></i>
                  </div>
                  <div>
                    <p class="mb-1">{{ activity.description }}</p>
                    <div class="d-flex align-items-center gap-2 small">
                      <span class="text-primary">{{ activity.user }}</span>
                      <span class="text-muted">{{ activity.time }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
                <i class="bi bi-info-circle me-2"></i>
                No recent activities
              </div>
            </div>
          </div>
        </div>
      </ng-container>
    </div>
  `
})
export class MeetingsComponent implements OnInit, OnDestroy {
  meetings: Meeting[] = [];
  showAll = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private meetingService: MeetingService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's meetings
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.meetingService.getMeetings(companyId, this.showAll ? undefined : 'Final').pipe(
          map(meetings => meetings.map(m => ({ ...m, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading meetings:', error);
        this.error = 'Failed to load meetings. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(meetings => {
      this.meetings = meetings;
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'meeting',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  openAddMeetingModal(): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(CreateMeetingModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.result.then(
      (newMeeting: Meeting) => {
        this.meetingService.createMeeting(companyId, newMeeting)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create meeting. Please try again.';
              console.error('Error creating meeting:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(meeting => {
              if (meeting) {
                return this.addActivity(companyId, {
                  type: 'added',
                  entityType: 'meeting',
                  entityId: meeting.id,
                  description: `New ${meeting.meetingType} (${meeting.id}) created`,
                  user: 'System'
                }).pipe(map(() => meeting));
              }
              return of(null);
            })
          )
          .subscribe(meeting => {
            if (meeting) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  viewMeeting(meeting: Meeting, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewMeetingModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.meeting = {...meeting};
    
    modalRef.result.then(
      (result: { action: string; meeting: Meeting } | undefined) => {
        if (result?.action === 'edit') {
          this.editMeeting(result.meeting);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editMeeting(meeting: Meeting): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(EditMeetingModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.meeting = {...meeting};
    
    modalRef.result.then(
      (updatedMeeting: Meeting) => {
        this.meetingService.updateMeeting(companyId, meeting.id, updatedMeeting)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update meeting. Please try again.';
              console.error('Error updating meeting:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                const statusChanged = meeting.status !== updatedMeeting.status;
                return this.addActivity(companyId, {
                  type: statusChanged ? 'status_changed' : 'updated',
                  entityType: 'meeting',
                  entityId: meeting.id,
                  description: statusChanged 
                    ? `${meeting.id} status changed to ${updatedMeeting.status}`
                    : `${meeting.id} details updated`,
                  user: 'System'
                }).pipe(map(() => result));
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeMeeting(meeting: Meeting): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove meeting ${meeting.id}?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.meetingService.deleteMeeting(companyId, meeting.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove meeting. Please try again.';
                console.error('Error removing meeting:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                return this.addActivity(companyId, {
                  type: 'removed',
                  entityType: 'meeting',
                  entityId: meeting.id,
                  description: `${meeting.id} removed from meetings register`,
                  user: 'System'
                });
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-GB');
  }

  getStatusClass(status: DocumentStatus): string {
    switch (status) {
      case 'Draft':
        return 'text-bg-warning';
      case 'Final':
        return 'text-bg-info';
      case 'Signed':
        return 'text-bg-success';
      default:
        return 'text-bg-secondary';
    }
  }

  toggleShowAll(): void {
    this.showAll = !this.showAll;
    this.refreshData();
  }

  getFilteredMeetings(): Meeting[] {
    if (!this.showAll) {
      // Show meetings from the last 3 months
      const threeMonthsAgo = new Date();
      threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
      return this.meetings.filter(m => new Date(m.meetingDate) >= threeMonthsAgo);
    }
    return this.meetings;
  }

  getTotalResolutions(): number {
    return this.meetings.reduce((sum, m) => sum + m.resolutions.length, 0);
  }

  getPassedResolutionsPercentage(): number {
    const totalResolutions = this.meetings.reduce((sum, m) => sum + m.resolutions.length, 0);
    if (totalResolutions === 0) return 0;

    const passedResolutions = this.meetings.reduce((sum, m) => 
      sum + m.resolutions.filter(r => r.outcome === 'Passed').length, 0);

    return Math.round((passedResolutions / totalResolutions) * 100);
  }

  getQuorumAchievedPercentage(): number {
    if (this.meetings.length === 0) return 0;

    const achievedCount = this.meetings.filter(m => m.quorum?.achieved).length;
    return Math.round((achievedCount / this.meetings.length) * 100);
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'added':
        return 'bi bi-plus-circle';
      case 'updated':
        return 'bi bi-pencil';
      case 'removed':
        return 'bi bi-trash';
      case 'status_changed':
        return 'bi bi-arrow-repeat';
      default:
        return 'bi bi-activity';
    }
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }
}

<div class="container-fluid p-4">
  <div class="row mb-4">
    <div class="col">
      <h1 class="mb-0">General Meetings Minutes</h1>
      <p class="text-muted">Record and manage company meetings, resolutions, and minutes</p>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Record Meeting</h5>
          <form [formGroup]="meetingForm" (ngSubmit)="onSubmit()">
            <div class="mb-3">
              <label class="form-label">Meeting Date</label>
              <input type="date" class="form-control" formControlName="date">
            </div>

            <div class="mb-3">
              <label class="form-label">Meeting Type</label>
              <select class="form-select" formControlName="type">
                <option value="">Select meeting type</option>
                <option *ngFor="let type of meetingTypes" [value]="type">{{ type }}</option>
              </select>
            </div>

            <div class="mb-3">
              <label class="form-label">Location</label>
              <input type="text" class="form-control" formControlName="location" placeholder="Enter meeting location">
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <label class="form-label">Start Time</label>
                <input type="time" class="form-control" formControlName="startTime">
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label">End Time</label>
                <input type="time" class="form-control" formControlName="endTime">
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Chairperson</label>
              <input type="text" class="form-control" formControlName="chairperson" placeholder="Enter chairperson name">
            </div>

            <div class="mb-3">
              <label class="form-label">Quorum Details</label>
              <input type="text" class="form-control" formControlName="quorum" placeholder="Enter quorum details">
            </div>

            <div class="mb-3">
              <label class="form-label">Attendees</label>
              <textarea class="form-control" formControlName="attendees" rows="3" placeholder="List all attendees"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Agenda</label>
              <textarea class="form-control" formControlName="agenda" rows="4" placeholder="Enter meeting agenda"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Resolutions</label>
              <textarea class="form-control" formControlName="resolutions" rows="4" placeholder="Enter resolutions passed"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Resolution Numbers</label>
              <input type="text" class="form-control" formControlName="resolutionNumbers" placeholder="Enter resolution reference numbers">
            </div>

            <div class="mb-3">
              <label class="form-label">Minutes</label>
              <textarea class="form-control" formControlName="minutes" rows="6" placeholder="Enter detailed meeting minutes"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Next Meeting Date (Optional)</label>
              <input type="date" class="form-control" formControlName="nextMeetingDate">
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="!meetingForm.valid">
              Record Meeting
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Meeting Records</h5>
          
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Location</th>
                  <th>Duration</th>
                  <th>Chairperson</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let meeting of meetings; let i = index">
                  <td>{{ formatDate(meeting.date) }}</td>
                  <td>{{ meeting.type }}</td>
                  <td>{{ meeting.location }}</td>
                  <td>{{ getDuration(meeting.startTime, meeting.endTime) }}</td>
                  <td>{{ meeting.chairperson }}</td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-sm btn-outline-primary me-1" (click)="downloadMinutes(meeting)">
                        <i class="bi bi-download"></i>
                      </button>
                      <button class="btn btn-sm btn-outline-danger" (click)="removeMeeting(i)">
                        <i class="bi bi-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                <tr *ngIf="meetings.length === 0">
                  <td colspan="6" class="text-center py-4 text-muted">
                    No meetings recorded yet
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// app/src/components/statutory/sections/meetings/Meetings.tsx
import React, { useState, useEffect } from 'react';
import MeetingModal from './MeetingModal';
import ImportMeetingModal from './ImportMeetingModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaFileImport, FaUsers, FaCheckCircle, FaTimesCircle, FaTrash, FaFileExport, FaFilePdf, FaFileExcel, FaCalendarAlt } from 'react-icons/fa';

interface Meeting {
  id?: string;
  meetingType: 'AGM' | 'EGM' | 'Board Meeting' | 'Committee Meeting';
  meetingDate: string;
  startTime: string;
  endTime: string;
  venue: string;
  chairperson: string;
  quorumRequired: number;
  quorumPresent: number;
  quorumAchieved: boolean;
  attendees: string[];
  agenda: string;
  status: 'Draft' | 'Scheduled' | 'In Progress' | 'Completed' | 'Cancelled';
  resolutions: Resolution[];
  company?: {
    name: string;
    legalName: string;
  };
}

interface Resolution {
  id?: string;
  title: string;
  type: 'Ordinary' | 'Special';
  description: string;
  outcome: 'Pending' | 'Passed' | 'Failed' | 'Withdrawn';
  proposedBy: string;
  secondedBy: string;
}

interface Activity {
  id: string;
  type: 'added' | 'update' | 'status_changed' | 'deletion';
  entityType: string;
  entityId: string;
  description: string;
  user: string;
  time: string;
}

const Meetings: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Draft' | 'Scheduled' | 'In Progress' | 'Completed' | 'Cancelled'>('All');
  const { user } = useAuth();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedMeeting, setSelectedMeeting] = useState<Meeting | undefined>(undefined);

  useEffect(() => {
    fetchMeetings();
    fetchRecentActivities();
  }, [statusFilter]);

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=meeting&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchMeetings = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/meetings/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setMeetings(response.data);
      } else {
        setMeetings([]);
        console.error('Expected array of meetings but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load meetings');
      console.error('Error fetching meetings:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/meetings/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `meetings.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting meetings:', error);
      alert('Failed to export meetings. Please try again.');
    }
  };

  const handleAddMeeting = () => {
    setSelectedMeeting(undefined);
    setShowAddModal(true);
  };

  const handleEditMeeting = (meeting: Meeting) => {
    setSelectedMeeting(meeting);
    setShowAddModal(true);
  };

  const handleDeleteMeeting = async (meeting: Meeting) => {
    if (window.confirm(`Are you sure you want to delete this ${meeting.meetingType}? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/meetings/${user?.companyId}/${meeting.id}`);
        fetchMeetings();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting meeting:', error);
        alert('Failed to delete meeting. Please try again.');
      }
    }
  };

  const handleModalSuccess = () => {
    fetchMeetings();
    fetchRecentActivities();
  };

  const getStatusBadgeVariant = (status: Meeting['status']) => {
    switch (status) {
      case 'Draft': return 'secondary';
      case 'Scheduled': return 'info';
      case 'In Progress': return 'warning';
      case 'Completed': return 'success';
      case 'Cancelled': return 'danger';
      default: return 'secondary';
    }
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <MeetingModal
        show={showAddModal}
        onHide={() => setShowAddModal(false)}
        meeting={selectedMeeting}
        onSuccess={handleModalSuccess}
      />
      {user?.companyId && (
        <ImportMeetingModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Meetings</h1>
            <p className="text-muted mb-0">Record and manage company meetings, resolutions and their details</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddMeeting}>
              <FaPlus className="me-2" /> Add Meeting
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Meetings</div>
                    <h3 className="mb-0">{meetings.length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaCalendarAlt className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Upcoming</div>
                    <h3 className="mb-0">{meetings.filter(m => m.status === 'Scheduled').length}</h3>
                  </div>
                  <div className="bg-info bg-opacity-10 p-3 rounded">
                    <FaUsers className="text-info" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Completed</div>
                    <h3 className="mb-0">{meetings.filter(m => m.status === 'Completed').length}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaCheckCircle className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Cancelled</div>
                    <h3 className="mb-0">{meetings.filter(m => m.status === 'Cancelled').length}</h3>
                  </div>
                  <div className="bg-danger bg-opacity-10 p-3 rounded">
                    <FaTimesCircle className="text-danger" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Meetings Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Draft' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Draft')}
                >
                  Draft
                </Button>
                <Button
                  variant={statusFilter === 'Scheduled' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Scheduled')}
                >
                  Scheduled
                </Button>
                <Button
                  variant={statusFilter === 'In Progress' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('In Progress')}
                >
                  In Progress
                </Button>
                <Button
                  variant={statusFilter === 'Completed' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Completed')}
                >
                  Completed
                </Button>
                <Button
                  variant={statusFilter === 'Cancelled' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Cancelled')}
                >
                  Cancelled
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Meeting Type</th>
                  <th>Date & Time</th>
                  <th>Venue</th>
                  <th>Chairperson</th>
                  <th>Quorum</th>
                  <th>Status</th>
                  {user?.role === 'super_admin' && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {meetings.map((meeting) => (
                  <tr key={meeting.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{meeting.meetingType}</div>
                          <div className="text-muted small">
                            {meeting.resolutions.length} Resolution{meeting.resolutions.length !== 1 ? 's' : ''}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div>
                        {new Date(meeting.meetingDate).toLocaleDateString('en-IE', {
                          day: '2-digit',
                          month: '2-digit',
                          year: 'numeric'
                        })}
                      </div>
                      <div className="text-muted small">
                        {new Date(meeting.startTime).toLocaleTimeString('en-IE', {
                          hour: '2-digit',
                          minute: '2-digit'
                        })} - {new Date(meeting.endTime).toLocaleTimeString('en-IE', {
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </div>
                    </td>
                    <td>{meeting.venue}</td>
                    <td>{meeting.chairperson}</td>
                    <td>
                      <div>
                        {meeting.quorumPresent}/{meeting.quorumRequired}
                      </div>
                      <div className="text-muted small">
                        {meeting.quorumAchieved ? 'Achieved' : 'Not Achieved'}
                      </div>
                    </td>
                    <td>
                      <Badge bg={getStatusBadgeVariant(meeting.status)}>
                        {meeting.status}
                      </Badge>
                    </td>
                    {user?.role === 'super_admin' && (
                      <td>{meeting.company?.name || meeting.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditMeeting(meeting)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      <Button
                        variant="link"
                        className="p-0"
                        onClick={() => handleDeleteMeeting(meeting)}
                      >
                        <FaTrash className="text-danger" />
                      </Button>
                    </td>
                  </tr>
                ))}
                {meetings.length === 0 && (
                  <tr>
                    <td colSpan={user?.role === 'super_admin' ? 8 : 7} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaCalendarAlt className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Meetings Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first meeting or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Meetings
                          </Button>
                          <Button variant="primary" onClick={handleAddMeeting}>
                            <FaPlus className="me-2" /> Add Meeting
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">Recent Activities</h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'added' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'update' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'status_changed' ? (
                            <FaCheckCircle className="text-warning" />
                          ) : activity.type === 'deletion' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {new Date(activity.time).toLocaleString('en-IE', {
                            day: '2-digit',
                            month: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default Meetings;
