// app/src/app/components/settings/users/modal/invite-user-modal.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgbActiveModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Role } from '../../settings.types';

@Component({
  selector: 'app-invite-user-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, NgbModule],
  template: `
    <div class="modal-header">
      <h4 class="modal-title">Invite User</h4>
      <button type="button" class="btn-close" (click)="activeModal.dismiss()"></button>
    </div>
    <form [formGroup]="inviteForm" (ngSubmit)="onSubmit()">
      <div class="modal-body">
        <div class="mb-3">
          <label for="email" class="form-label">Email Address</label>
          <input
            type="email"
            class="form-control"
            id="email"
            formControlName="email"
            placeholder="Enter email address"
          />
          <div class="form-text text-danger" *ngIf="inviteForm.get('email')?.errors?.['required'] && inviteForm.get('email')?.touched">
            Email is required
          </div>
          <div class="form-text text-danger" *ngIf="inviteForm.get('email')?.errors?.['email'] && inviteForm.get('email')?.touched">
            Please enter a valid email address
          </div>
        </div>

        <div class="mb-3">
          <label for="role" class="form-label">Role</label>
          <select class="form-select" id="role" formControlName="role">
            <option value="">Select a role</option>
            <option value="Super Administrator">Super Administrator</option>
            <option value="Administrator">Administrator</option>
            <option value="Billing Administrator">Billing Administrator</option>
            <option value="User Manager">User Manager</option>
          </select>
          <div class="form-text text-danger" *ngIf="inviteForm.get('role')?.errors?.['required'] && inviteForm.get('role')?.touched">
            Role is required
          </div>
        </div>

        <div class="mb-3">
          <label for="department" class="form-label">Department</label>
          <input
            type="text"
            class="form-control"
            id="department"
            formControlName="department"
            placeholder="Enter department"
          />
        </div>

        <div class="mb-3">
          <label for="jobTitle" class="form-label">Job Title</label>
          <input
            type="text"
            class="form-control"
            id="jobTitle"
            formControlName="jobTitle"
            placeholder="Enter job title"
          />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" (click)="activeModal.dismiss()">Cancel</button>
        <button type="submit" class="btn btn-primary" [disabled]="!inviteForm.valid">
          Send Invitation
        </button>
      </div>
    </form>
  `
})
export class InviteUserModalComponent {
  inviteForm: FormGroup;

  constructor(
    public activeModal: NgbActiveModal,
    private fb: FormBuilder
  ) {
    this.inviteForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      role: ['', Validators.required],
      department: [''],
      jobTitle: ['']
    });
  }

  onSubmit(): void {
    if (this.inviteForm.valid) {
      const formValue = this.inviteForm.value;
      const selectedRole = formValue.role;

      // Create role object
      const role: Role = {
        id: selectedRole,
        name: selectedRole,
        description: '',
        scope: 'Company',
        permissions: [],
        status: 'Active',
        isCustom: false,
        isSystem: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        metadata: {
          allowedModules: []
        }
      };

      // Return the form data with role object
      this.activeModal.close({
        email: formValue.email,
        role,
        department: formValue.department,
        jobTitle: formValue.jobTitle
      });
    }
  }
}

// app-react/src/components/settings/sections/users/InviteUserModal.tsx
import React, { useState } from 'react';
import { UsersService, handleApiError } from '../../../../services/settings';

interface InviteUserModalProps {
  show: boolean;
  onHide: () => void;
  onSuccess: () => void;
}

const InviteUserModal: React.FC<InviteUserModalProps> = ({ show, onHide, onSuccess }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    email: '',
    role: '',
    department: '',
    jobTitle: ''
  });

  const validateForm = () => {
    if (!formData.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      setError('Please enter a valid email address');
      return false;
    }
    if (!formData.role) {
      setError('Role is required');
      return false;
    }
    return true;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;

    try {
      setLoading(true);
      setError(null);

      // Create role object
      const role = {
        id: formData.role,
        name: formData.role,
        description: '',
        scope: 'Company' as const,
        permissions: [],
        status: 'Active' as const,
        isCustom: false,
        isSystem: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        metadata: {
          allowedModules: []
        }
      };

      await UsersService.inviteUser({
        email: formData.email,
        roleId: role.id,
        department: formData.department,
        jobTitle: formData.jobTitle
      });

      onSuccess();
      onHide();
    } catch (err) {
      setError(handleApiError(err));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={`modal ${show ? 'd-block' : ''}`} tabIndex={-1}>
      <div className="modal-dialog">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">Invite User</h5>
            <button type="button" className="btn-close" onClick={onHide}></button>
          </div>
          <div className="modal-body">
            {error && (
              <div className="alert alert-danger mb-3">
                {error}
              </div>
            )}
            <form onSubmit={handleSubmit}>
              <div className="mb-3">
                <label className="form-label">Email Address</label>
                <input
                  type="email"
                  className="form-control"
                  value={formData.email}
                  onChange={e => setFormData(prev => ({ ...prev, email: e.target.value }))}
                  placeholder="Enter email address"
                  required
                />
              </div>

              <div className="mb-3">
                <label className="form-label">Role</label>
                <select
                  className="form-select"
                  value={formData.role}
                  onChange={e => setFormData(prev => ({ ...prev, role: e.target.value }))}
                  required
                >
                  <option value="">Select a role</option>
                  <option value="Super Administrator">Super Administrator</option>
                  <option value="Administrator">Administrator</option>
                  <option value="Billing Administrator">Billing Administrator</option>
                  <option value="User Manager">User Manager</option>
                </select>
              </div>

              <div className="mb-3">
                <label className="form-label">Department</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.department}
                  onChange={e => setFormData(prev => ({ ...prev, department: e.target.value }))}
                  placeholder="Enter department"
                />
              </div>

              <div className="mb-3">
                <label className="form-label">Job Title</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.jobTitle}
                  onChange={e => setFormData(prev => ({ ...prev, jobTitle: e.target.value }))}
                  placeholder="Enter job title"
                />
              </div>
            </form>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onHide}>
              Cancel
            </button>
            <button
              type="button"
              className="btn btn-primary"
              onClick={handleSubmit}
              disabled={loading}
            >
              {loading ? 'Sending...' : 'Send Invitation'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InviteUserModal;
