// app-react/src/components/statutory/sections/board-minutes/BoardMinutes.tsx
import React, { useState, useEffect } from 'react';
import BoardMinuteModal from './BoardMinuteModal';
import ImportBoardMinuteModal from './ImportBoardMinuteModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaFileImport, FaBook, FaCheckCircle, FaTimesCircle, FaTrash, FaFileExport, FaFilePdf, FaFileExcel, FaCalendarAlt } from 'react-icons/fa';

interface BoardMinute {
  id?: string;
  meetingType: 'AGM' | 'EGM' | 'Board Meeting' | 'Committee Meeting';
  meetingDate: string;
  startTime: string;
  endTime: string;
  venue: string;
  chairperson: string;
  attendees: string[];
  content: string;
  discussions: Discussion[];
  resolutions: Resolution[];
  status: 'Draft' | 'Final' | 'Signed';
  company?: {
    name: string;
    legalName: string;
  };
}

interface Discussion {
  id?: string;
  topic: string;
  details: string;
  decisions: string;
  actionItems: ActionItem[];
}

interface ActionItem {
  id?: string;
  task: string;
  assignee: string;
  dueDate: string;
  status: 'Pending' | 'In Progress' | 'Completed' | 'Cancelled';
}

interface Resolution {
  id?: string;
  title: string;
  type: 'Ordinary' | 'Special';
  description: string;
  outcome: 'Pending' | 'Passed' | 'Failed' | 'Withdrawn';
  proposedBy: string;
  secondedBy: string;
}

interface Activity {
  id: string;
  type: 'added' | 'update' | 'status_changed' | 'deletion';
  entityType: string;
  entityId: string;
  description: string;
  user: string;
  time: string;
}

const BoardMinutes: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [minutes, setMinutes] = useState<BoardMinute[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Draft' | 'Final' | 'Signed'>('All');
  const { user } = useAuth();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedMinute, setSelectedMinute] = useState<BoardMinute | undefined>(undefined);

  useEffect(() => {
    fetchMinutes();
    fetchRecentActivities();
  }, [statusFilter]);

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=board-minute&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchMinutes = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/board-minutes/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setMinutes(response.data);
      } else {
        setMinutes([]);
        console.error('Expected array of board minutes but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load board minutes');
      console.error('Error fetching board minutes:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/board-minutes/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `board-minutes.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting board minutes:', error);
      alert('Failed to export board minutes. Please try again.');
    }
  };

  const handleAddMinute = () => {
    setSelectedMinute(undefined);
    setShowAddModal(true);
  };

  const handleEditMinute = (minute: BoardMinute) => {
    setSelectedMinute(minute);
    setShowAddModal(true);
  };

  const handleDeleteMinute = async (minute: BoardMinute) => {
    if (window.confirm(`Are you sure you want to delete this ${minute.meetingType} minute? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/board-minutes/${user?.companyId}/${minute.id}`);
        fetchMinutes();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting board minute:', error);
        alert('Failed to delete board minute. Please try again.');
      }
    }
  };

  const handleModalSuccess = () => {
    fetchMinutes();
    fetchRecentActivities();
  };

  const getStatusBadgeVariant = (status: BoardMinute['status']) => {
    switch (status) {
      case 'Draft': return 'secondary';
      case 'Final': return 'primary';
      case 'Signed': return 'success';
      default: return 'secondary';
    }
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <BoardMinuteModal
        show={showAddModal}
        onHide={() => setShowAddModal(false)}
        minute={selectedMinute}
        onSuccess={handleModalSuccess}
      />
      {user?.companyId && (
        <ImportBoardMinuteModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Board Minutes</h1>
            <p className="text-muted mb-0">Record and manage board meeting minutes, discussions and their resolutions</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddMinute}>
              <FaPlus className="me-2" /> Add Minute
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Minutes</div>
                    <h3 className="mb-0">{minutes.length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaBook className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Draft</div>
                    <h3 className="mb-0">{minutes.filter(m => m.status === 'Draft').length}</h3>
                  </div>
                  <div className="bg-secondary bg-opacity-10 p-3 rounded">
                    <FaCalendarAlt className="text-secondary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Final</div>
                    <h3 className="mb-0">{minutes.filter(m => m.status === 'Final').length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaCheckCircle className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Signed</div>
                    <h3 className="mb-0">{minutes.filter(m => m.status === 'Signed').length}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaTimesCircle className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Board Minutes Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Draft' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Draft')}
                >
                  Draft
                </Button>
                <Button
                  variant={statusFilter === 'Final' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Final')}
                >
                  Final
                </Button>
                <Button
                  variant={statusFilter === 'Signed' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Signed')}
                >
                  Signed
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Meeting Type</th>
                  <th>Date & Time</th>
                  <th>Venue</th>
                  <th>Chairperson</th>
                  <th>Discussions</th>
                  <th>Status</th>
                  {user?.role === 'super_admin' && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {minutes.map((minute) => (
                  <tr key={minute.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{minute.meetingType}</div>
                          <div className="text-muted small">
                            {minute.resolutions.length} Resolution{minute.resolutions.length !== 1 ? 's' : ''}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div>
                        {new Date(minute.meetingDate).toLocaleDateString('en-IE', {
                          day: '2-digit',
                          month: '2-digit',
                          year: 'numeric'
                        })}
                      </div>
                      <div className="text-muted small">
                        {new Date(minute.startTime).toLocaleTimeString('en-IE', {
                          hour: '2-digit',
                          minute: '2-digit'
                        })} - {new Date(minute.endTime).toLocaleTimeString('en-IE', {
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </div>
                    </td>
                    <td>{minute.venue}</td>
                    <td>{minute.chairperson}</td>
                    <td>
                      <div>
                        {minute.discussions.length} Discussion{minute.discussions.length !== 1 ? 's' : ''}
                      </div>
                      <div className="text-muted small">
                        {minute.discussions.reduce((total, d) => total + d.actionItems.length, 0)} Action Item{minute.discussions.reduce((total, d) => total + d.actionItems.length, 0) !== 1 ? 's' : ''}
                      </div>
                    </td>
                    <td>
                      <Badge bg={getStatusBadgeVariant(minute.status)}>
                        {minute.status}
                      </Badge>
                    </td>
                    {user?.role === 'super_admin' && (
                      <td>{minute.company?.name || minute.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditMinute(minute)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      <Button
                        variant="link"
                        className="p-0"
                        onClick={() => handleDeleteMinute(minute)}
                      >
                        <FaTrash className="text-danger" />
                      </Button>
                    </td>
                  </tr>
                ))}
                {minutes.length === 0 && (
                  <tr>
                    <td colSpan={user?.role === 'super_admin' ? 8 : 7} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaBook className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Board Minutes Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first board minute or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Minutes
                          </Button>
                          <Button variant="primary" onClick={handleAddMinute}>
                            <FaPlus className="me-2" /> Add Minute
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">Recent Activities</h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'added' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'update' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'status_changed' ? (
                            <FaCheckCircle className="text-warning" />
                          ) : activity.type === 'deletion' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {new Date(activity.time).toLocaleString('en-IE', {
                            day: '2-digit',
                            month: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default BoardMinutes;

// app/src/app/components/statutory/board-minutes/board-minutes.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, of } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, map } from 'rxjs/operators';

import { CreateBoardMinuteModalComponent } from './modal/create-board-minute-modal.component';
import { EditBoardMinuteModalComponent } from './modal/edit-board-minute-modal.component';
import { ViewBoardMinuteModalComponent } from './modal/view-board-minute-modal.component';
import { ConfirmModalComponent } from './modal/confirm-modal.component';

import { BoardMinuteService } from '../../../services/statutory/board-minute.service';
import { CompanyService } from '../../../services/settings/company.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { AuthService } from '../../../services/auth/auth.service';

import { BoardMinute, Activity, ActivityResponse } from '../statutory.types';

type MinuteStatus = 'Draft' | 'Final' | 'Signed';

@Component({
  selector: 'app-board-minutes',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateBoardMinuteModalComponent,
    EditBoardMinuteModalComponent,
    ViewBoardMinuteModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Header -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 class="h3 mb-2">Board Minutes Register</h1>
          <p class="text-muted mb-0">Record and manage board meetings and resolutions</p>
        </div>
        <div>
          <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddMinuteModal()">
            <i class="bi bi-plus-lg"></i>
            <span>Add Board Meeting</span>
          </button>
        </div>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading" class="text-center py-5">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>

      <!-- Error State -->
      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <!-- Content -->
      <ng-container *ngIf="!loading && !error">
        <!-- Metrics -->
        <div class="row g-3 mb-4">
          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Total Meetings</span>
                  <i class="bi bi-calendar-event fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ minutes.length }}</h3>
                <small class="text-muted">Recorded meetings</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Resolutions</span>
                  <i class="bi bi-file-text fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getTotalResolutions() }}</h3>
                <small class="text-muted">Total resolutions</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Passed</span>
                  <i class="bi bi-check-circle fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getPassedResolutionsPercentage() }}%</h3>
                <small class="text-muted">Resolution success rate</small>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="card h-100">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <span class="text-muted">Actions</span>
                  <i class="bi bi-list-task fs-4 text-primary"></i>
                </div>
                <h3 class="mb-0">{{ getCompletedActionsPercentage() }}%</h3>
                <small class="text-muted">Action items completed</small>
              </div>
            </div>
          </div>
        </div>

        <!-- Minutes Table -->
        <div class="card mb-4">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Board Meetings</h5>
            <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAll()">
              <i [class]="showAll ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
              <span>{{ showAll ? 'Show Recent Only' : 'Show All Meetings' }}</span>
            </button>
          </div>
          <div class="table-responsive">
            <table class="table table-hover mb-0">
              <thead class="bg-light">
                <tr>
                  <th class="text-uppercase small fw-semibold text-secondary">ID</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Date</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Chairperson</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Resolutions</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                  <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let minute of getFilteredMinutes()">
                  <td>
                    <div class="d-flex align-items-center gap-2">
                      <i class="bi bi-calendar-event text-secondary"></i>
                      <a href="#" class="text-decoration-none" (click)="viewMinute(minute, $event)">
                        {{ minute.id }}
                      </a>
                    </div>
                  </td>
                  <td>{{ formatDate(minute.meetingDate) }}</td>
                  <td>{{ minute.chairperson }}</td>
                  <td>
                    <div class="d-flex align-items-center gap-2">
                      <span class="badge text-bg-secondary">{{ minute.resolutions.length }}</span>
                      <div class="small">
                        <span class="text-success">{{ getPassedResolutions(minute) }}</span> /
                        <span class="text-danger">{{ getRejectedResolutions(minute) }}</span> /
                        <span class="text-warning">{{ getDeferredResolutions(minute) }}</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <div class="d-flex align-items-center gap-2">
                      <span class="badge text-bg-secondary">{{ getTotalActions(minute) }}</span>
                      <div class="small">
                        {{ getCompletedActions(minute) }} completed
                      </div>
                    </div>
                  </td>
                  <td>
                    <span [class]="'badge ' + getStatusClass(minute.status)">
                      {{ minute.status }}
                    </span>
                  </td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-link btn-sm text-body px-2" (click)="viewMinute(minute)" title="View Details">
                        <i class="bi bi-eye"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-body px-2" (click)="editMinute(minute)" title="Edit">
                        <i class="bi bi-pencil"></i>
                      </button>
                      <button class="btn btn-link btn-sm text-danger px-2" (click)="removeMinute(minute)" title="Remove">
                        <i class="bi bi-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                <tr *ngIf="getFilteredMinutes().length === 0">
                  <td colspan="7" class="text-center py-4 text-muted">
                    <i class="bi bi-info-circle me-2"></i>
                    No board meetings found
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Recent Activities -->
        <div class="card">
          <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <h5 class="mb-0">Recent Activities</h5>
            <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
              <i class="bi bi-arrow-clockwise me-1"></i>
              <span>Refresh</span>
            </button>
          </div>
          <div class="card-body">
            <div class="list-group list-group-flush">
              <div class="list-group-item px-0" *ngFor="let activity of recentActivities">
                <div class="d-flex align-items-start gap-3">
                  <div class="bg-light rounded p-2">
                    <i [class]="getActivityIcon(activity.type)"></i>
                  </div>
                  <div>
                    <p class="mb-1">{{ activity.description }}</p>
                    <div class="d-flex align-items-center gap-2 small">
                      <span class="text-primary">{{ activity.user }}</span>
                      <span class="text-muted">{{ activity.time }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
                <i class="bi bi-info-circle me-2"></i>
                No recent activities
              </div>
            </div>
          </div>
        </div>
      </ng-container>
    </div>
  `
})
export class BoardMinutesComponent implements OnInit, OnDestroy {
  minutes: BoardMinute[] = [];
  showAll = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private boardMinuteService: BoardMinuteService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's board minutes
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.boardMinuteService.getBoardMinutes(companyId, this.showAll ? undefined : 'Final').pipe(
          map(minutes => minutes.map(m => ({ ...m, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading board minutes:', error);
        this.error = 'Failed to load board minutes. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(minutesArrays => {
      this.minutes = minutesArrays.flat();
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'board-minute',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  openAddMinuteModal(): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(CreateBoardMinuteModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.result.then(
      (newMinute: BoardMinute) => {
        this.boardMinuteService.createBoardMinute(companyId, newMinute)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create board minute. Please try again.';
              console.error('Error creating board minute:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(minute => {
              if (minute) {
                return this.addActivity(companyId, {
                  type: 'added',
                  entityType: 'board-minute',
                  entityId: minute.id,
                  description: `New board meeting ${minute.id} created`,
                  user: 'System'
                }).pipe(map(() => minute));
              }
              return of(null);
            })
          )
          .subscribe(minute => {
            if (minute) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  viewMinute(minute: BoardMinute, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewBoardMinuteModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.minute = {...minute};
    
    modalRef.result.then(
      (result: { action: string; minute: BoardMinute } | undefined) => {
        if (result?.action === 'edit') {
          this.editMinute(result.minute);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editMinute(minute: BoardMinute): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(EditBoardMinuteModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.minute = {...minute};
    
    modalRef.result.then(
      (updatedMinute: BoardMinute) => {
        this.boardMinuteService.updateBoardMinute(companyId, minute.id, updatedMinute)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update board minute. Please try again.';
              console.error('Error updating board minute:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                const statusChanged = minute.status !== updatedMinute.status;
                return this.addActivity(companyId, {
                  type: statusChanged ? 'status_changed' : 'updated',
                  entityType: 'board-minute',
                  entityId: minute.id,
                  description: statusChanged 
                    ? `${minute.id} status changed to ${updatedMinute.status}`
                    : `${minute.id} details updated`,
                  user: 'System'
                }).pipe(map(() => result));
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeMinute(minute: BoardMinute): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove board meeting ${minute.id}?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.boardMinuteService.deleteBoardMinute(companyId, minute.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove board minute. Please try again.';
                console.error('Error removing board minute:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                return this.addActivity(companyId, {
                  type: 'removed',
                  entityType: 'board-minute',
                  entityId: minute.id,
                  description: `${minute.id} removed from board minutes register`,
                  user: 'System'
                });
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-GB');
  }

  getStatusClass(status: MinuteStatus): string {
    switch (status) {
      case 'Draft':
        return 'text-bg-warning';
      case 'Final':
        return 'text-bg-info';
      case 'Signed':
        return 'text-bg-success';
      default:
        return 'text-bg-secondary';
    }
  }

  toggleShowAll(): void {
    this.showAll = !this.showAll;
    this.refreshData();
  }

  getFilteredMinutes(): BoardMinute[] {
    if (!this.showAll) {
      // Show meetings from the last 3 months
      const threeMonthsAgo = new Date();
      threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
      return this.minutes.filter(m => new Date(m.meetingDate) >= threeMonthsAgo);
    }
    return this.minutes;
  }

  getTotalResolutions(): number {
    return this.minutes.reduce((sum, m) => sum + m.resolutions.length, 0);
  }

  getPassedResolutions(minute: BoardMinute): number {
    return minute.resolutions.filter(r => r.outcome === 'Passed').length;
  }

  getRejectedResolutions(minute: BoardMinute): number {
    return minute.resolutions.filter(r => r.outcome === 'Rejected').length;
  }

  getDeferredResolutions(minute: BoardMinute): number {
    return minute.resolutions.filter(r => r.outcome === 'Deferred').length;
  }

  getPassedResolutionsPercentage(): number {
    const totalResolutions = this.minutes.reduce((sum, m) => sum + m.resolutions.length, 0);
    if (totalResolutions === 0) return 0;

    const passedResolutions = this.minutes.reduce((sum, m) => 
      sum + m.resolutions.filter(r => r.outcome === 'Passed').length, 0);

    return Math.round((passedResolutions / totalResolutions) * 100);
  }

  getTotalActions(minute: BoardMinute): number {
    return minute.discussions.reduce((sum, d) => sum + (d.actionItems?.length || 0), 0);
  }

  getCompletedActions(minute: BoardMinute): number {
    return minute.discussions.reduce((sum, d) => 
      sum + (d.actionItems?.filter(a => a.status === 'Completed').length || 0), 0);
  }

  getCompletedActionsPercentage(): number {
    const totalActions = this.minutes.reduce((sum, m) => 
      sum + m.discussions.reduce((dSum, d) => dSum + (d.actionItems?.length || 0), 0), 0);
    
    if (totalActions === 0) return 0;

    const completedActions = this.minutes.reduce((sum, m) => 
      sum + m.discussions.reduce((dSum, d) => 
        dSum + (d.actionItems?.filter(a => a.status === 'Completed').length || 0), 0), 0);

    return Math.round((completedActions / totalActions) * 100);
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'added':
        return 'bi bi-plus-circle';
      case 'updated':
        return 'bi bi-pencil';
      case 'removed':
        return 'bi bi-trash';
      case 'status_changed':
        return 'bi bi-arrow-repeat';
      default:
        return 'bi bi-activity';
    }
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }
}

<div class="container-fluid p-4">
  <div class="row mb-4">
    <div class="col">
      <h1 class="mb-0">Board Minutes Register</h1>
      <p class="text-muted">Record and manage board meetings and resolutions</p>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Record Board Meeting</h5>
          <form [formGroup]="meetingForm" (ngSubmit)="onSubmit()">
            <div class="mb-3">
              <label class="form-label">Meeting Date</label>
              <input type="date" class="form-control" formControlName="date">
            </div>

            <div class="mb-3">
              <label class="form-label">Location</label>
              <input type="text" class="form-control" formControlName="location" placeholder="Enter meeting location">
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <label class="form-label">Start Time</label>
                <input type="time" class="form-control" formControlName="startTime">
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label">End Time</label>
                <input type="time" class="form-control" formControlName="endTime">
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Chairperson</label>
              <input type="text" class="form-control" formControlName="chairperson" placeholder="Enter chairperson name">
            </div>

            <div class="mb-3">
              <label class="form-label">Quorum Details</label>
              <input type="text" class="form-control" formControlName="quorum" placeholder="Enter quorum details">
            </div>

            <div class="mb-3">
              <label class="form-label">Directors Present</label>
              <textarea class="form-control" formControlName="attendees" rows="3" placeholder="List all attending directors"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Apologies</label>
              <textarea class="form-control" formControlName="apologies" rows="2" placeholder="List directors who sent apologies (optional)"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Agenda</label>
              <textarea class="form-control" formControlName="agenda" rows="4" placeholder="Enter meeting agenda"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Discussions</label>
              <textarea class="form-control" formControlName="discussions" rows="6" placeholder="Enter meeting discussions"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Decisions</label>
              <textarea class="form-control" formControlName="decisions" rows="4" placeholder="Enter decisions made"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Actions</label>
              <textarea class="form-control" formControlName="actions" rows="4" placeholder="Enter action items and assignments"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Resolution Numbers</label>
              <input type="text" class="form-control" formControlName="resolutionNumbers" placeholder="Enter resolution reference numbers">
            </div>

            <div class="mb-3">
              <label class="form-label">Next Meeting Date (Optional)</label>
              <input type="date" class="form-control" formControlName="nextMeetingDate">
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="!meetingForm.valid">
              Record Meeting
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Board Meetings</h5>
          
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Location</th>
                  <th>Duration</th>
                  <th>Chairperson</th>
                  <th>Decisions</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let meeting of meetings; let i = index">
                  <td>{{ formatDate(meeting.date) }}</td>
                  <td>{{ meeting.location }}</td>
                  <td>{{ getDuration(meeting.startTime, meeting.endTime) }}</td>
                  <td>{{ meeting.chairperson }}</td>
                  <td>
                    <span class="text-truncate d-inline-block" style="max-width: 200px;">
                      {{ meeting.decisions }}
                    </span>
                  </td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-sm btn-outline-primary me-1" (click)="downloadMinutes(meeting)">
                        <i class="bi bi-download"></i>
                      </button>
                      <button class="btn btn-sm btn-outline-danger" (click)="removeMeeting(i)">
                        <i class="bi bi-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                <tr *ngIf="meetings.length === 0">
                  <td colspan="6" class="text-center py-4 text-muted">
                    No board meetings recorded yet
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
