// app-react/src/components/settings/sections/notifications/Notifications.tsx
import React, { useState, useEffect } from 'react';
import { NotificationSettings } from './types';
import { Button, Card, Row, Col, Form, ListGroup } from 'react-bootstrap';

const Notifications: React.FC = () => {
  const [settings, setSettings] = useState<NotificationSettings>({
    email: {
      accountUpdates: true,
      securityAlerts: true,
      marketingUpdates: false
    },
    push: {
      taskUpdates: true,
      comments: true,
      reminders: true
    },
    schedule: {
      quietHoursStart: 20,
      quietHoursEnd: 7,
      weekendsOnly: false
    }
  });

  const handleEmailChange = (setting: keyof typeof settings.email) => {
    setSettings(prev => ({
      ...prev,
      email: {
        ...prev.email,
        [setting]: !prev.email[setting]
      }
    }));
  };

  const handlePushChange = (setting: keyof typeof settings.push) => {
    setSettings(prev => ({
      ...prev,
      push: {
        ...prev.push,
        [setting]: !prev.push[setting]
      }
    }));
  };

  const handleScheduleChange = (
    e: React.ChangeEvent<HTMLSelectElement | HTMLInputElement>
  ) => {
    const { name, value, type } = e.target;
    setSettings(prev => ({
      ...prev,
      schedule: {
        ...prev.schedule,
        [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : Number(value)
      }
    }));
  };

  const handleSave = () => {
    // TODO: Save settings to API
    console.log('Save settings:', settings);
  };

  const formatTime = (hour: number) => {
    const period = hour >= 12 ? 'PM' : 'AM';
    const displayHour = hour % 12 || 12;
    return `${displayHour}:00 ${period}`;
  };

  return (
    <div className="container-fluid py-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 className="h3 mb-0">Notification Settings</h1>
          <p className="text-muted mb-0">Configure how and when you receive notifications</p>
        </div>
      </div>

      <Row className="mb-4">
        <Col md={3}>
          <Card className="h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <div className="text-muted mb-1">Email Notifications</div>
                  <h3 className="mb-0">
                    {Object.values(settings.email).filter(Boolean).length}
                  </h3>
                  <small className="text-muted">Active email alerts</small>
                </div>
                <div className="bg-primary bg-opacity-10 p-3 rounded">
                  <i className="bi bi-envelope text-primary" style={{ fontSize: '24px' }}></i>
                </div>
              </div>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <div className="text-muted mb-1">Push Notifications</div>
                  <h3 className="mb-0">
                    {Object.values(settings.push).filter(Boolean).length}
                  </h3>
                  <small className="text-muted">Active push alerts</small>
                </div>
                <div className="bg-success bg-opacity-10 p-3 rounded">
                  <i className="bi bi-bell text-success" style={{ fontSize: '24px' }}></i>
                </div>
              </div>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <div className="text-muted mb-1">Quiet Hours</div>
                  <h3 className="mb-0">{settings.schedule.quietHoursEnd < settings.schedule.quietHoursStart ? 
                    24 - settings.schedule.quietHoursStart + settings.schedule.quietHoursEnd :
                    settings.schedule.quietHoursEnd - settings.schedule.quietHoursStart}h</h3>
                  <small className="text-muted">Do not disturb period</small>
                </div>
                <div className="bg-warning bg-opacity-10 p-3 rounded">
                  <i className="bi bi-moon text-warning" style={{ fontSize: '24px' }}></i>
                </div>
              </div>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <div className="text-muted mb-1">Total Alerts</div>
                  <h3 className="mb-0">
                    {Object.values(settings.email).filter(Boolean).length + 
                     Object.values(settings.push).filter(Boolean).length}
                  </h3>
                  <small className="text-muted">Active notifications</small>
                </div>
                <div className="bg-info bg-opacity-10 p-3 rounded">
                  <i className="bi bi-app-indicator text-info" style={{ fontSize: '24px' }}></i>
                </div>
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      {/* Email Notifications */}
      <Card className="mb-4">
        <Card.Header className="bg-white py-3">
          <h5 className="mb-0">Email Notifications</h5>
        </Card.Header>
        <Card.Body>
          <ListGroup variant="flush">
            {/* Account */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Account Updates</h6>
                  <p className="text-muted small mb-0">Important updates about your account</p>
                </div>
                <Form.Check
                  type="switch"
                  id="accountUpdates"
                  checked={settings.email.accountUpdates}
                  onChange={() => handleEmailChange('accountUpdates')}
                />
              </div>
            </ListGroup.Item>

            {/* Security */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Security Alerts</h6>
                  <p className="text-muted small mb-0">Security-related notifications and alerts</p>
                </div>
                <Form.Check
                  type="switch"
                  id="securityAlerts"
                  checked={settings.email.securityAlerts}
                  onChange={() => handleEmailChange('securityAlerts')}
                />
              </div>
            </ListGroup.Item>

            {/* Marketing */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Marketing Updates</h6>
                  <p className="text-muted small mb-0">News about products and features</p>
                </div>
                <Form.Check
                  type="switch"
                  id="marketingUpdates"
                  checked={settings.email.marketingUpdates}
                  onChange={() => handleEmailChange('marketingUpdates')}
                />
              </div>
            </ListGroup.Item>
          </ListGroup>
        </Card.Body>
      </Card>

      {/* Push Notifications */}
      <Card className="mb-4">
        <Card.Header className="bg-white py-3">
          <h5 className="mb-0">Push Notifications</h5>
        </Card.Header>
        <Card.Body>
          <ListGroup variant="flush">
            {/* Task Updates */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Task Updates</h6>
                  <p className="text-muted small mb-0">Notifications about task assignments and updates</p>
                </div>
                <Form.Check
                  type="switch"
                  id="taskUpdates"
                  checked={settings.push.taskUpdates}
                  onChange={() => handlePushChange('taskUpdates')}
                />
              </div>
            </ListGroup.Item>

            {/* Comments */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Comments</h6>
                  <p className="text-muted small mb-0">When someone comments on your items</p>
                </div>
                <Form.Check
                  type="switch"
                  id="comments"
                  checked={settings.push.comments}
                  onChange={() => handlePushChange('comments')}
                />
              </div>
            </ListGroup.Item>

            {/* Reminders */}
            <ListGroup.Item className="py-3">
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <h6 className="mb-1">Reminders</h6>
                  <p className="text-muted small mb-0">Task and deadline reminders</p>
                </div>
                <Form.Check
                  type="switch"
                  id="reminders"
                  checked={settings.push.reminders}
                  onChange={() => handlePushChange('reminders')}
                />
              </div>
            </ListGroup.Item>
          </ListGroup>
        </Card.Body>
      </Card>

      {/* Notification Schedule */}
      <Card className="mb-4">
        <Card.Header className="bg-white py-3">
          <h5 className="mb-0">Notification Schedule</h5>
        </Card.Header>
        <Card.Body>
          <Row>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Quiet Hours Start</Form.Label>
                <Form.Select
                  name="quietHoursStart"
                  value={settings.schedule.quietHoursStart}
                  onChange={handleScheduleChange}
                >
                  {Array.from({ length: 24 }, (_, i) => (
                    <option key={i} value={i}>
                      {formatTime(i)}
                    </option>
                  ))}
                </Form.Select>
              </Form.Group>
            </Col>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Quiet Hours End</Form.Label>
                <Form.Select
                  name="quietHoursEnd"
                  value={settings.schedule.quietHoursEnd}
                  onChange={handleScheduleChange}
                >
                  {Array.from({ length: 24 }, (_, i) => (
                    <option key={i} value={i}>
                      {formatTime(i)}
                    </option>
                  ))}
                </Form.Select>
              </Form.Group>
            </Col>
          </Row>
          <Form.Check
            type="checkbox"
            id="weekendsOnly"
            label="Apply quiet hours on weekends only"
            name="weekendsOnly"
            checked={settings.schedule.weekendsOnly}
            onChange={handleScheduleChange}
            className="mt-3"
          />
        </Card.Body>
      </Card>

      {/* Save Changes */}
      <div className="d-flex justify-content-end">
        <Button variant="primary" onClick={handleSave}>
          Save Notification Settings
        </Button>
      </div>
    </div>
  );
};

export default Notifications;

// app/src/app/components/settings/notifications/notifications.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-settings-notifications',
  template: `
    <div class="container-fluid p-4">
      <div class="row mb-4">
        <div class="col">
          <h2 class="mb-2">Notification Settings</h2>
          <p class="text-secondary mb-0">Configure how and when you receive notifications</p>
        </div>
      </div>

      <!-- Email Notifications -->
      <div class="card border-0 shadow-sm">
        <div class="card-body p-4">
          <h5 class="mb-4">Email Notifications</h5>
          <div class="list-group">
            <!-- Account -->
            <div class="list-group-item border-0 bg-light rounded mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Account Updates</h6>
                  <p class="text-secondary small mb-0">Important updates about your account</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="accountUpdates" checked>
                </div>
              </div>
            </div>

            <!-- Security -->
            <div class="list-group-item border-0 bg-light rounded mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Security Alerts</h6>
                  <p class="text-secondary small mb-0">Security-related notifications and alerts</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="securityAlerts" checked>
                </div>
              </div>
            </div>

            <!-- Marketing -->
            <div class="list-group-item border-0 bg-light rounded">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Marketing Updates</h6>
                  <p class="text-secondary small mb-0">News about products and features</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="marketingUpdates">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Push Notifications -->
      <div class="card border-0 shadow-sm mt-4">
        <div class="card-body p-4">
          <h5 class="mb-4">Push Notifications</h5>
          <div class="list-group">
            <!-- Task Updates -->
            <div class="list-group-item border-0 bg-light rounded mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Task Updates</h6>
                  <p class="text-secondary small mb-0">Notifications about task assignments and updates</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="taskUpdates" checked>
                </div>
              </div>
            </div>

            <!-- Comments -->
            <div class="list-group-item border-0 bg-light rounded mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Comments</h6>
                  <p class="text-secondary small mb-0">When someone comments on your items</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="comments" checked>
                </div>
              </div>
            </div>

            <!-- Reminders -->
            <div class="list-group-item border-0 bg-light rounded">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h6 class="mb-1">Reminders</h6>
                  <p class="text-secondary small mb-0">Task and deadline reminders</p>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="reminders" checked>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Notification Schedule -->
      <div class="card border-0 shadow-sm mt-4">
        <div class="card-body p-4">
          <h5 class="mb-4">Notification Schedule</h5>
          <div class="row g-4">
            <div class="col-md-6">
              <div class="mb-3">
                <label class="form-label">Quiet Hours Start</label>
                <select class="form-select">
                  <option value="18">6:00 PM</option>
                  <option value="19">7:00 PM</option>
                  <option value="20" selected>8:00 PM</option>
                  <option value="21">9:00 PM</option>
                  <option value="22">10:00 PM</option>
                </select>
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label class="form-label">Quiet Hours End</label>
                <select class="form-select">
                  <option value="6">6:00 AM</option>
                  <option value="7" selected>7:00 AM</option>
                  <option value="8">8:00 AM</option>
                  <option value="9">9:00 AM</option>
                  <option value="10">10:00 AM</option>
                </select>
              </div>
            </div>
          </div>
          <div class="form-check mt-3">
            <input class="form-check-input" type="checkbox" id="weekendsOnly">
            <label class="form-check-label" for="weekendsOnly">
              Apply quiet hours on weekends only
            </label>
          </div>
        </div>
      </div>

      <!-- Save Changes -->
      <div class="mt-4">
        <button class="btn btn-primary">Save Notification Settings</button>
      </div>
    </div>
  `,
  standalone: true,
  imports: [CommonModule, RouterModule]
})
export class SettingsNotificationsComponent {
  constructor(private modalService: NgbModal) {}
}
