// app/src/app/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ComplianceSidebarComponent } from '../compliance/compliance-sidebar.component';
import { TaxSidebarComponent } from '../tax/tax-sidebar/tax-sidebar.component';
import { SettingsSidebarComponent } from '../settings/settings-sidebar.component';
import { HelpSidebarComponent } from '../help/help-sidebar/help-sidebar.component';
import { StatutorySidebarComponent } from '../statutory/statutory-sidebar.component';
import { AuthService } from '../../services/auth/auth.service';
import { CompanyService } from '../../services/settings/company.service';
import { firstValueFrom } from 'rxjs';

type SectionType = 'statutory' | 'compliance' | 'tax' | 'settings' | 'help';

interface ModuleConfig {
  icon: string;
  title: string;
}

@Component({
  selector: 'app-sidebar',
  template: `
    <div class="position-fixed h-100 bg-light border-end overflow-hidden"
         [class.translate-middle-x]="!isExpanded && isMobile"
         [ngStyle]="{
           'left': '48px',
           'width': isExpanded ? '220px' : '40px',
           'transition': 'width 0.3s ease, transform 0.3s ease',
           'z-index': 'var(--z-index-fixed)'
         }">
      <!-- Header -->
      <div class="d-flex align-items-center justify-content-between px-3 py-2 border-bottom">
        <div class="d-flex align-items-center" *ngIf="isExpanded">
          <i [class]="'bi fs-5 me-2 ' + getModuleIcon()"></i>
          <span class="small">{{ companyName || getModuleTitle() }}</span>
        </div>
        <button class="btn btn-link btn-sm p-0 text-body-secondary" 
                [class.ms-auto]="!isExpanded"
                (click)="onToggleSidebar()">
          <i class="bi" [class.bi-chevron-left]="isExpanded" [class.bi-chevron-right]="!isExpanded"></i>
        </button>
      </div>

      <!-- Module-specific Sidebar -->
      <div class="h-100 overflow-auto" style="scrollbar-width: thin;">
        <ng-container [ngSwitch]="activeSection">
          <app-statutory-sidebar *ngSwitchCase="'statutory'" [isExpanded]="isExpanded"></app-statutory-sidebar>
          <app-compliance-sidebar *ngSwitchCase="'compliance'"></app-compliance-sidebar>
          <app-tax-sidebar *ngSwitchCase="'tax'"></app-tax-sidebar>
          <app-settings-sidebar *ngSwitchCase="'settings'"></app-settings-sidebar>
          <app-help-sidebar *ngSwitchCase="'help'"></app-help-sidebar>
        </ng-container>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
    }

    .overflow-auto::-webkit-scrollbar {
      width: 4px;
    }

    .overflow-auto::-webkit-scrollbar-track {
      background: var(--bs-gray-100);
    }

    .overflow-auto::-webkit-scrollbar-thumb {
      background: var(--bs-gray-300);
      border-radius: 2px;
    }

    .overflow-auto::-webkit-scrollbar-thumb:hover {
      background: var(--bs-gray-400);
    }

    @media (max-width: 768px) {
      :host {
        left: 40px;
      }
    }
  `],
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    StatutorySidebarComponent,
    ComplianceSidebarComponent,
    TaxSidebarComponent,
    SettingsSidebarComponent,
    HelpSidebarComponent
  ]
})
export class SidebarComponent implements OnInit {
  @Input() isExpanded = true;
  @Input() isMobile = false;
  @Input() activeSection: SectionType = 'statutory';

  @Output() toggleSidebar = new EventEmitter<void>();

  companyName: string | null = null;

  private readonly moduleConfigs: Record<SectionType, ModuleConfig> = {
    statutory: { icon: 'bi-journal-bookmark', title: 'Statutory' },
    compliance: { icon: 'bi-shield-check', title: 'Compliance' },
    tax: { icon: 'bi-calculator', title: 'Tax' },
    settings: { icon: 'bi-gear', title: 'Settings' },
    help: { icon: 'bi-question-circle', title: 'Help' }
  };

  constructor(
    private authService: AuthService,
    private companyService: CompanyService
  ) {}

  async ngOnInit() {
    const user = this.authService.currentUserValue;
    if (user?.companyId) {
      try {
        const company = await firstValueFrom(this.companyService.getCompany(user.companyId));
        this.companyName = company.name;
      } catch (error) {
        console.error('Error loading company:', error);
      }
    }
  }

  onToggleSidebar() {
    this.toggleSidebar.emit();
  }

  getModuleIcon(): string {
    return this.moduleConfigs[this.activeSection]?.icon || 'bi-grid';
  }

  getModuleTitle(): string {
    return this.moduleConfigs[this.activeSection]?.title || '';
  }
}

<!-- Main Sidebar -->
<div class="sidebar" [class.show]="isExpanded">
  <!-- Sidebar Header -->
  <div class="sidebar-header">
    <div class="logo-container">
      <img src="assets/logo.png" alt="Bradán">
      <span class="logo-text">Bradán</span>
    </div>
  </div>

  <!-- Navigation Container with Scroll -->
  <div class="nav-container">
    <!-- Books Section -->
    <div class="nav-section" *ngIf="activeSection === 'books'">
      <div class="section-header">
        <span>BOOKS</span>
      </div>
      <ul class="nav-items">
        <li>
          <a routerLink="/books/dashboard" routerLinkActive="active">
            <i class="bi bi-grid"></i>
            <span class="nav-label">Dashboard</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/accounting" routerLinkActive="active">
            <i class="bi bi-journal-text"></i>
            <span class="nav-label">Accounting</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/banking" routerLinkActive="active">
            <i class="bi bi-bank"></i>
            <span class="nav-label">Banking</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/invoicing" routerLinkActive="active">
            <i class="bi bi-receipt"></i>
            <span class="nav-label">Invoicing</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/bills" routerLinkActive="active">
            <i class="bi bi-cash-stack"></i>
            <span class="nav-label">Bills</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/expenses" routerLinkActive="active">
            <i class="bi bi-wallet2"></i>
            <span class="nav-label">Expenses</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/payroll" routerLinkActive="active">
            <i class="bi bi-people"></i>
            <span class="nav-label">Payroll</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/projects" routerLinkActive="active">
            <i class="bi bi-kanban"></i>
            <span class="nav-label">Projects</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/reports" routerLinkActive="active">
            <i class="bi bi-bar-chart"></i>
            <span class="nav-label">Reports</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/files" routerLinkActive="active">
            <i class="bi bi-folder"></i>
            <span class="nav-label">Files</span>
          </a>
        </li>
        <li>
          <a routerLink="/books/contacts" routerLinkActive="active">
            <i class="bi bi-person-lines-fill"></i>
            <span class="nav-label">Contacts</span>
          </a>
        </li>
      </ul>
    </div>

    <!-- CRM Section -->
    <div class="nav-section" *ngIf="activeSection === 'crm'">
      <div class="section-header">
        <span>CRM</span>
      </div>
      <ul class="nav-items">
        <li>
          <a routerLink="/crm/dashboard" routerLinkActive="active">
            <i class="bi bi-grid"></i>
            <span class="nav-label">Dashboard</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/contacts" routerLinkActive="active">
            <i class="bi bi-person"></i>
            <span class="nav-label">Contacts</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/companies" routerLinkActive="active">
            <i class="bi bi-building"></i>
            <span class="nav-label">Companies</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/marketing" routerLinkActive="active">
            <i class="bi bi-megaphone"></i>
            <span class="nav-label">Marketing Hub</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/sales" routerLinkActive="active">
            <i class="bi bi-graph-up"></i>
            <span class="nav-label">Sales Hub</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/service" routerLinkActive="active">
            <i class="bi bi-headset"></i>
            <span class="nav-label">Service Hub</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/operations" routerLinkActive="active">
            <i class="bi bi-gear"></i>
            <span class="nav-label">Operations Hub</span>
          </a>
        </li>
        <li>
          <a routerLink="/crm/cms" routerLinkActive="active">
            <i class="bi bi-window"></i>
            <span class="nav-label">CMS Hub</span>
          </a>
        </li>
      </ul>
    </div>

    <!-- Carbon Section -->
    <div class="nav-section" *ngIf="activeSection === 'carbon'">
      <div class="section-header">
        <span>CARBON</span>
      </div>
      <ul class="nav-items">
        <li>
          <a routerLink="/carbon/dashboard" routerLinkActive="active">
            <i class="bi bi-grid"></i>
            <span class="nav-label">Dashboard</span>
          </a>
        </li>
        <li>
          <a routerLink="/carbon/emissions" routerLinkActive="active">
            <i class="bi bi-cloud"></i>
            <span class="nav-label">Emissions</span>
          </a>
        </li>
        <li>
          <a routerLink="/carbon/reports" routerLinkActive="active">
            <i class="bi bi-file-earmark-text"></i>
            <span class="nav-label">Reports</span>
          </a>
        </li>
        <li>
          <a routerLink="/carbon/offsets" routerLinkActive="active">
            <i class="bi bi-tree"></i>
            <span class="nav-label">Offsets</span>
          </a>
        </li>
        <li>
          <a routerLink="/carbon/goals" routerLinkActive="active">
            <i class="bi bi-bullseye"></i>
            <span class="nav-label">Goals</span>
          </a>
        </li>
        <li>
          <a routerLink="/carbon/settings" routerLinkActive="active">
            <i class="bi bi-gear"></i>
            <span class="nav-label">Settings</span>
          </a>
        </li>
      </ul>
    </div>

    <!-- Tax Section -->
    <div class="nav-section" *ngIf="activeSection === 'tax'">
      <div class="section-header">
        <span>TAX</span>
      </div>
      <ul class="nav-items">
        <li>
          <a routerLink="/tax/dashboard" routerLinkActive="active">
            <i class="bi bi-grid"></i>
            <span class="nav-label">Dashboard</span>
          </a>
        </li>
        <li>
          <a routerLink="/tax/vat" routerLinkActive="active">
            <i class="bi bi-receipt"></i>
            <span class="nav-label">VAT</span>
          </a>
        </li>
        <li>
          <a routerLink="/tax/income-tax" routerLinkActive="active">
            <i class="bi bi-person-badge"></i>
            <span class="nav-label">Income Tax</span>
          </a>
        </li>
        <li>
          <a routerLink="/tax/corporation-tax" routerLinkActive="active">
            <i class="bi bi-building"></i>
            <span class="nav-label">Corporation Tax</span>
          </a>
        </li>
        <li>
          <a routerLink="/tax/capital-gains" routerLinkActive="active">
            <i class="bi bi-graph-up-arrow"></i>
            <span class="nav-label">Capital Gains</span>
          </a>
        </li>
        <li>
          <a routerLink="/tax/payroll-tax" routerLinkActive="active">
            <i class="bi bi-people"></i>
            <span class="nav-label">Payroll Tax</span>
          </a>
        </li>
      </ul>
    </div>

    <!-- Settings Section -->
    <div class="nav-section" *ngIf="activeSection === 'settings'">
      <div class="section-header">
        <span>SETTINGS</span>
      </div>
      <ul class="nav-items">
        <li>
          <a routerLink="/settings/profile" routerLinkActive="active">
            <i class="bi bi-person"></i>
            <span class="nav-label">Profile</span>
          </a>
        </li>
        <li>
          <a routerLink="/settings/organization" routerLinkActive="active">
            <i class="bi bi-building"></i>
            <span class="nav-label">Organization</span>
          </a>
        </li>
        <li>
          <a routerLink="/settings/preferences" routerLinkActive="active">
            <i class="bi bi-sliders"></i>
            <span class="nav-label">Preferences</span>
          </a>
        </li>
      </ul>
    </div>

    <!-- Help Section -->
    <div class="nav-section" *ngIf="activeSection === 'help'">
      <div class="section-header">
        <span>HELP & SUPPORT</span>
      </div>
      <ul class="nav-items">
        <li>
          <a href="#" (click)="openDocumentation($event)">
            <i class="bi bi-book"></i>
            <span class="nav-label">Documentation</span>
          </a>
        </li>
        <li>
          <a href="#" (click)="openSupport($event)">
            <i class="bi bi-headset"></i>
            <span class="nav-label">Support</span>
          </a>
        </li>
        <li>
          <a href="#" (click)="openFeedback($event)">
            <i class="bi bi-chat-dots"></i>
            <span class="nav-label">Feedback</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

<!-- Mobile Overlay -->
<div class="sidebar-overlay" 
     [class.active]="isExpanded && isMobile" 
     (click)="toggleExpanded()">
</div>

// app/src/components/shared/Sidebar.tsx
import React, { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import StatutorySidebar from '../statutory/StatutorySidebar';
import SettingsSidebar from '../settings/SettingsSidebar';
import HelpSidebar from '../help/HelpSidebar';
import CRMSidebar from '../crm/CRMSidebar';

type SectionType = 'statutory' | 'compliance' | 'tax' | 'crm' | 'settings' | 'help';

interface ModuleConfig {
  icon: string;
  title: string;
}

interface SidebarProps {
  isExpanded: boolean;
  isMobile: boolean;
  activeSection: SectionType;
  onToggleSidebar: () => void;
}

const moduleConfigs: Record<SectionType, ModuleConfig> = {
  statutory: { icon: 'bi-journal-bookmark', title: 'Statutory' },
  compliance: { icon: 'bi-shield-check', title: 'Compliance' },
  tax: { icon: 'bi-calculator', title: 'Tax' },
  settings: { icon: 'bi-gear', title: 'Settings' },
  help: { icon: 'bi-question-circle', title: 'Help' },
  crm: { icon: 'bi-people', title: 'CRM' }
};

const Sidebar: React.FC<SidebarProps> = ({
  isExpanded,
  isMobile,
  activeSection,
  onToggleSidebar
}) => {
  const { user } = useAuth();
  const [companyName, setCompanyName] = useState<string | null>(null);

  useEffect(() => {
    const fetchCompanyDetails = async () => {
      if (user?.companyId) {
        try {
          const response = await fetch(`http://localhost:3000/api/settings/companies/${user.companyId}`, {
            headers: {
              'Authorization': `Bearer ${localStorage.getItem('token')}`,
              'Content-Type': 'application/json'
            }
          });
          if (response.ok) {
            const company = await response.json();
            setCompanyName(company.name);
          }
        } catch (error) {
          console.error('Error loading company:', error);
        }
      }
    };

    fetchCompanyDetails();
  }, [user?.companyId]);

  const getModuleIcon = (): string => {
    return moduleConfigs[activeSection]?.icon || 'bi-grid';
  };

  const getModuleTitle = (): string => {
    return moduleConfigs[activeSection]?.title || '';
  };

  const renderSidebar = () => {
    switch (activeSection) {
      case 'statutory':
        return <StatutorySidebar isExpanded={isExpanded} />;
      case 'settings':
        return <SettingsSidebar isExpanded={isExpanded} />;
      case 'help':
        return <HelpSidebar isExpanded={isExpanded} />;
      case 'crm':
        return <CRMSidebar isExpanded={isExpanded} />;
      default:
        return <div className="p-4">Coming Soon</div>;
    }
  };

  return (
    <div
      className="position-fixed h-100 bg-light border-end overflow-hidden"
      style={{
        left: '48px',
        width: isExpanded ? '220px' : '40px',
        transition: 'width 0.3s ease, transform 0.3s ease',
        zIndex: 1020,
        transform: !isExpanded && isMobile ? 'translateX(-50%)' : 'none'
      }}
    >
      {/* Header */}
      <div className="d-flex align-items-center justify-content-between px-3 py-2 border-bottom">
        {isExpanded && (
          <div className="d-flex align-items-center">
            <i className={`bi fs-5 me-2 ${getModuleIcon()}`}></i>
            <span className="small">{companyName || getModuleTitle()}</span>
          </div>
        )}
        <button
          className={`btn btn-link btn-sm p-0 text-body-secondary ${!isExpanded ? 'ms-auto' : ''}`}
          onClick={onToggleSidebar}
        >
          <i className={`bi ${isExpanded ? 'bi-chevron-left' : 'bi-chevron-right'}`}></i>
        </button>
      </div>

      {/* Module-specific Sidebar */}
      <div className="h-100 overflow-auto" style={{ scrollbarWidth: 'thin' }}>
        {renderSidebar()}
      </div>

      <style>
        {`
          .overflow-auto::-webkit-scrollbar {
            width: 4px;
          }

          .overflow-auto::-webkit-scrollbar-track {
            background: var(--bs-gray-100);
          }

          .overflow-auto::-webkit-scrollbar-thumb {
            background: var(--bs-gray-300);
            border-radius: 2px;
          }

          .overflow-auto::-webkit-scrollbar-thumb:hover {
            background: var(--bs-gray-400);
          }

          @media (max-width: 768px) {
            .sidebar {
              left: 40px;
            }
          }
        `}
      </style>
    </div>
  );
};

export default Sidebar;
