// app/src/components/statutory/sections/shareholders/Shareholders.tsx
import React, { useState, useEffect } from 'react';
import ShareholderModal from './ShareholderModal';
import ImportShareholderModal from './ImportShareholderModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaFileImport, FaUsers, FaUserCheck, FaUserMinus, FaClock, FaTrash, FaFileExport, FaFilePdf, FaFileExcel } from 'react-icons/fa';

import { Shareholder, Activity } from '../../../../services/statutory/types';
import { formatDDMMYYYY } from '@bradan/shared';

const Shareholders: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [shareholders, setShareholders] = useState<Shareholder[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Active' | 'Inactive'>('All');
  const { user } = useAuth();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedShareholder, setSelectedShareholder] = useState<Shareholder | undefined>(undefined);

  useEffect(() => {
    fetchShareholders();
    fetchRecentActivities();
  }, [statusFilter]);

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=shareholder&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchShareholders = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/shareholders/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setShareholders(response.data);
      } else {
        setShareholders([]);
        console.error('Expected array of shareholders but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load shareholders');
      console.error('Error fetching shareholders:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/shareholders/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `shareholders.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting shareholders:', error);
      alert('Failed to export shareholders. Please try again.');
    }
  };

  const handleAddShareholder = () => {
    setSelectedShareholder(undefined);
    setShowAddModal(true);
  };

  const handleEditShareholder = (shareholder: Shareholder) => {
    setSelectedShareholder(shareholder);
    setShowAddModal(true);
  };

  const handleDeleteShareholder = async (shareholder: Shareholder) => {
    if (window.confirm(`Are you sure you want to delete ${shareholder.firstName} ${shareholder.lastName}? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/shareholders/${user?.companyId}/${shareholder.id}`);
        fetchShareholders();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting shareholder:', error);
        alert('Failed to delete shareholder. Please try again.');
      }
    }
  };

  const handleModalSuccess = () => {
    fetchShareholders();
    fetchRecentActivities();
  };

  const getTotalOrdinaryShares = () => {
    return shareholders.reduce((sum, s) => sum + (s.ordinaryShares || 0), 0);
  };

  const getTotalPreferentialShares = () => {
    return shareholders.reduce((sum, s) => sum + (s.preferentialShares || 0), 0);
  };

  const getTotalShares = () => {
    return getTotalOrdinaryShares() + getTotalPreferentialShares();
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <ShareholderModal
        show={showAddModal}
        onHide={() => setShowAddModal(false)}
        shareholder={selectedShareholder}
        onSuccess={handleModalSuccess}
      />
      {user?.companyId && (
        <ImportShareholderModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Shareholders Register</h1>
            <p className="text-muted mb-0">Record and manage company shareholders and their holdings</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddShareholder}>
              <FaPlus className="me-2" /> Add Shareholder
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Active Shareholders</div>
                    <h3 className="mb-0">{shareholders.filter(s => s.status === 'Active').length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaUsers className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Ordinary Shares</div>
                    <h3 className="mb-0">{getTotalOrdinaryShares()}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaUserCheck className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Preferential Shares</div>
                    <h3 className="mb-0">{getTotalPreferentialShares()}</h3>
                  </div>
                  <div className="bg-info bg-opacity-10 p-3 rounded">
                    <FaUserCheck className="text-info" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={3}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Shares</div>
                    <h3 className="mb-0">{getTotalShares()}</h3>
                  </div>
                  <div className="bg-secondary bg-opacity-10 p-3 rounded">
                    <FaUserMinus className="text-secondary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Shareholders Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Active' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Active')}
                >
                  Active
                </Button>
                <Button
                  variant={statusFilter === 'Inactive' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Inactive')}
                >
                  Inactive
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Name</th>
                  <th>Ordinary Shares</th>
                  <th>Preferential Shares</th>
                  <th>Total Shares</th>
                  <th>Date Acquired</th>
                  <th>Status</th>
                  {user?.roles?.includes('super_admin') && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {shareholders.map((shareholder) => (
                  <tr key={shareholder.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{`${shareholder.title} ${shareholder.firstName} ${shareholder.lastName}`}</div>
                          <div className="text-muted small">{shareholder.email}</div>
                        </div>
                      </div>
                    </td>
                    <td>{shareholder.ordinaryShares}</td>
                    <td>{shareholder.preferentialShares}</td>
                    <td>{shareholder.ordinaryShares + shareholder.preferentialShares}</td>
                    <td>{formatDDMMYYYY(new Date(shareholder.dateAcquired))}</td>
                    <td>
                      <Badge bg={shareholder.status === 'Active' ? 'success' : 'secondary'}>
                        {shareholder.status}
                      </Badge>
                    </td>
                    {user?.roles?.includes('super_admin') && (
                      <td>{shareholder.company?.name || shareholder.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditShareholder(shareholder)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      <Button
                        variant="link"
                        className="p-0"
                        onClick={() => handleDeleteShareholder(shareholder)}
                      >
                        <FaTrash className="text-danger" />
                      </Button>
                    </td>
                  </tr>
                ))}
                {shareholders.length === 0 && (
                  <tr>
                    <td colSpan={user?.roles?.includes('super_admin') ? 8 : 7} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaUsers className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Shareholders Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first shareholder or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Shareholders
                          </Button>
                          <Button variant="primary" onClick={handleAddShareholder}>
                            <FaPlus className="me-2" /> Add Shareholder
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">
                <FaClock className="me-2" />
                Recent Activities
              </h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'added' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'updated' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'removed' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {formatDDMMYYYY(new Date(activity.time))}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default Shareholders;

// app/src/app/components/statutory/shareholders/shareholders.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, of } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, map } from 'rxjs/operators';

import { CreateShareholderModalComponent } from './modal/create-shareholder-modal.component';
import { EditShareholderModalComponent } from './modal/edit-shareholder-modal.component';
import { ViewShareholderModalComponent } from './modal/view-shareholder-modal.component';
import { ConfirmModalComponent } from './modal/confirm-modal.component';

import { ShareholderService } from '../../../services/statutory/shareholder.service';
import { CompanyService } from '../../../services/settings/company.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { AuthService } from '../../../services/auth/auth.service';

import { Shareholder, Activity, ActivityResponse } from '../statutory.types';

@Component({
  selector: 'app-shareholders',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateShareholderModalComponent,
    EditShareholderModalComponent,
    ViewShareholderModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Error Alert -->
      <div class="alert alert-danger alert-dismissible fade show" role="alert" *ngIf="error">
        {{ error }}
        <button type="button" class="btn-close" (click)="error = null"></button>
      </div>

      <!-- Loading State -->
      <div class="text-center py-5" *ngIf="loading">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>

      <!-- Content (only show when not loading) -->
      <ng-container *ngIf="!loading">
        <!-- Header -->
        <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 class="h3 mb-2">Shareholders Register</h1>
          <p class="text-muted mb-0">Record and manage company shareholders and their holdings</p>
        </div>
        <div>
          <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddShareholderModal()">
            <i class="bi bi-plus-lg"></i>
            <span>Add Shareholder</span>
          </button>
        </div>
      </div>

      <!-- Metrics -->
      <div class="row g-3 mb-4">
        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Active Shareholders</span>
                <i class="bi bi-people fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getActiveShareholders().length }}</h3>
              <small class="text-muted">Currently holding shares</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Ordinary Shares</span>
                <i class="bi bi-diagram-3 fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getTotalOrdinaryShares() }}</h3>
              <small class="text-muted">Total ordinary shares issued</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Preferential Shares</span>
                <i class="bi bi-diagram-2 fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getTotalPreferentialShares() }}</h3>
              <small class="text-muted">Total preferential shares issued</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Total Shares</span>
                <i class="bi bi-pie-chart fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getTotalShares() }}</h3>
              <small class="text-muted">Combined total shares</small>
            </div>
          </div>
        </div>
      </div>

      <!-- Shareholders Table -->
      <div class="card mb-4">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Current Shareholders</h5>
          <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAll()">
            <i [class]="showAll ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
            <span>{{ showAll ? 'Show Active Only' : 'Show All Shareholders' }}</span>
          </button>
        </div>
        <div class="table-responsive">
          <table class="table table-hover mb-0">
            <thead class="bg-light">
              <tr>
                <th class="text-uppercase small fw-semibold text-secondary">Name</th>
                <th class="text-uppercase small fw-semibold text-secondary">Ordinary Shares</th>
                <th class="text-uppercase small fw-semibold text-secondary">Preferential Shares</th>
                <th class="text-uppercase small fw-semibold text-secondary">Total Shares</th>
                <th class="text-uppercase small fw-semibold text-secondary">Date Acquired</th>
                <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let shareholder of getFilteredShareholders()">
                <td>
                  <div class="d-flex align-items-center gap-2">
                    <i class="bi bi-person-circle text-secondary"></i>
                    <a href="#" class="text-decoration-none" (click)="viewShareholder(shareholder, $event)">
                      {{ getFullName(shareholder) }}
                    </a>
                  </div>
                </td>
                <td>{{ shareholder.shares?.ordinary || 0 }}</td>
                <td>{{ shareholder.shares?.preferential || 0 }}</td>
                <td>{{ (shareholder.shares?.ordinary || 0) + (shareholder.shares?.preferential || 0) }}</td>
                <td>{{ formatDate(shareholder.dateAcquired) }}</td>
                <td>
                  <span [class]="'badge ' + (shareholder.status === 'Active' ? 'text-bg-success' : 'text-bg-secondary')">
                    {{ shareholder.status }}
                  </span>
                </td>
                <td>
                  <div class="btn-group">
                    <button class="btn btn-link btn-sm text-body px-2" (click)="viewShareholder(shareholder)" title="View Details">
                      <i class="bi bi-eye"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-body px-2" (click)="editShareholder(shareholder)" title="Edit">
                      <i class="bi bi-pencil"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-danger px-2" (click)="removeShareholder(shareholder)" title="Remove">
                      <i class="bi bi-trash"></i>
                    </button>
                  </div>
                </td>
              </tr>
              <tr *ngIf="getFilteredShareholders().length === 0">
                <td colspan="7" class="text-center py-4 text-muted">
                  <i class="bi bi-info-circle me-2"></i>
                  No shareholders found
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Recent Activities -->
      <div class="card">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Recent Activities</h5>
          <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
            <i class="bi bi-arrow-clockwise me-1"></i>
            <span>Refresh</span>
          </button>
        </div>
        <div class="card-body">
          <div class="list-group list-group-flush">
            <ng-container *ngFor="let activity of recentActivities">
              <div class="list-group-item px-0">
                <div class="d-flex align-items-start gap-3">
                  <div class="bg-light rounded p-2">
                    <i [class]="getActivityIcon(activity.type)"></i>
                  </div>
                  <div>
                    <p class="mb-1">{{ activity.description }}</p>
                    <div class="d-flex align-items-center gap-2 small">
                      <span class="text-primary">{{ activity.user }}</span>
                      <span class="text-muted">{{ activity.time }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </ng-container>
            <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
              <i class="bi bi-info-circle me-2"></i>
              No recent activities
            </div>
          </div>
        </div>
      </div>
  `
})
export class ShareholdersComponent implements OnInit, OnDestroy {
  shareholders: Shareholder[] = [];
  showAll = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private shareholderService: ShareholderService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's shareholders
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.shareholderService.getShareholders(companyId, this.showAll ? undefined : 'Active').pipe(
          map(shareholders => shareholders.map(s => ({ ...s, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading shareholders:', error);
        this.error = 'Failed to load shareholders. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(shareholdersArrays => {
      this.shareholders = shareholdersArrays.flat();
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'shareholder',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  openAddShareholderModal(): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(CreateShareholderModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.result.then(
      (newShareholder: Shareholder) => {
        this.shareholderService.createShareholder(companyId, newShareholder)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create shareholder. Please try again.';
              console.error('Error creating shareholder:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(shareholder => {
              if (shareholder) {
                return this.addActivity(companyId, {
                  type: 'added',
                  entityType: 'shareholder',
                  entityId: shareholder.id,
                  description: `${this.getFullName(shareholder)} added as shareholder with ${shareholder.shares.ordinary + shareholder.shares.preferential} shares`,
                  user: 'System'
                }).pipe(map(() => shareholder));
              }
              return of(null);
            })
          )
          .subscribe(shareholder => {
            if (shareholder) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  viewShareholder(shareholder: Shareholder, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewShareholderModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.shareholder = {...shareholder};
    
    modalRef.result.then(
      (result: { action: string; shareholder: Shareholder } | undefined) => {
        if (result?.action === 'edit') {
          this.editShareholder(result.shareholder);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editShareholder(shareholder: Shareholder): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(EditShareholderModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.shareholder = {...shareholder};
    
    modalRef.result.then(
      (updatedShareholder: Shareholder) => {
        this.shareholderService.updateShareholder(companyId, shareholder.id, updatedShareholder)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update shareholder. Please try again.';
              console.error('Error updating shareholder:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                return this.addActivity(companyId, {
                  type: 'updated',
                  entityType: 'shareholder',
                  entityId: shareholder.id,
                  description: `${this.getFullName(shareholder)}'s details updated`,
                  user: 'System'
                }).pipe(map(() => result));
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeShareholder(shareholder: Shareholder): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove ${this.getFullName(shareholder)} from the shareholders register?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.shareholderService.deleteShareholder(companyId, shareholder.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove shareholder. Please try again.';
                console.error('Error removing shareholder:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                return this.addActivity(companyId, {
                  type: 'removed',
                  entityType: 'shareholder',
                  entityId: shareholder.id,
                  description: `${this.getFullName(shareholder)} removed from shareholders register`,
                  user: 'System'
                });
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-GB');
  }

  getFullName(shareholder: Shareholder): string {
    return `${shareholder.title} ${shareholder.firstName} ${shareholder.lastName}`;
  }

  toggleShowAll(): void {
    this.showAll = !this.showAll;
    this.refreshData();
  }

  getFilteredShareholders(): Shareholder[] {
    return this.showAll 
      ? this.shareholders 
      : this.shareholders.filter(s => s.status === 'Active');
  }

  getActiveShareholders(): Shareholder[] {
    return this.shareholders.filter(s => s.status === 'Active');
  }

  getTotalOrdinaryShares(): number {
    return this.shareholders.reduce((sum, s) => sum + (s.shares?.ordinary || 0), 0);
  }

  getTotalPreferentialShares(): number {
    return this.shareholders.reduce((sum, s) => sum + (s.shares?.preferential || 0), 0);
  }

  getTotalShares(): number {
    return this.getTotalOrdinaryShares() + this.getTotalPreferentialShares();
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'added':
        return 'bi bi-person-plus';
      case 'updated':
        return 'bi bi-pencil';
      case 'removed':
        return 'bi bi-trash';
      case 'status_changed':
        return 'bi bi-arrow-repeat';
      default:
        return 'bi bi-activity';
    }
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }
}

<div class="shareholders">
  <div class="container-fluid p-4">
    <!-- Header -->
    <div class="page-header d-flex justify-content-between align-items-center mb-4">
      <div>
        <h1>Shareholders Register</h1>
        <p class="text-muted mb-0">Record and manage company shareholders and their shareholdings</p>
      </div>
      <button class="btn btn-primary" (click)="openAddShareholderModal()">
        <i class="bi bi-plus-lg me-2"></i>
        Add Shareholder
      </button>
    </div>

    <!-- Metrics -->
    <div class="row g-4 mb-4">
      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Total Shareholders</span>
            <i class="bi bi-people"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getTotalShareholdersCount() }}</div>
            <div class="metric-details">Active shareholders</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Individual Holders</span>
            <i class="bi bi-person"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getIndividualShareholdersCount() }}</div>
            <div class="metric-details">Individual shareholders</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Corporate Holders</span>
            <i class="bi bi-building"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getCorporateShareholdersCount() }}</div>
            <div class="metric-details">Corporate shareholders</div>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="metric-card">
          <div class="metric-header">
            <span class="metric-title">Total Value</span>
            <i class="bi bi-currency-pound"></i>
          </div>
          <div class="metric-body">
            <div class="metric-value">{{ getTotalShareValue() | currency:'GBP':'symbol':'1.0-0' }}</div>
            <div class="metric-details">Total share value</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Shareholders Table -->
    <div class="card mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Current Shareholders</h5>
        <div class="btn-group">
          <button class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-download me-2"></i>Export
          </button>
          <button class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-printer me-2"></i>Print
          </button>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>NAME/COMPANY</th>
              <th>SHARE CLASS</th>
              <th>SHARES HELD</th>
              <th>PERCENTAGE</th>
              <th>ACQUISITION DATE</th>
              <th>STATUS</th>
              <th>ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let shareholder of shareholders; let i = index">
              <td>
                <div class="d-flex align-items-center">
                  <div class="shareholder-icon me-2">
                    <i [class]="shareholder.shareholderType === 'individual' ? 'bi bi-person-circle' : 'bi bi-building'"></i>
                  </div>
                  <div>
                    <ng-container *ngIf="shareholder.shareholderType === 'individual'">
                      {{ shareholder.title }} {{ shareholder.firstName }} {{ shareholder.lastName }}
                    </ng-container>
                    <ng-container *ngIf="shareholder.shareholderType === 'corporate'">
                      Company #{{ shareholder.companyNumber }}
                    </ng-container>
                  </div>
                </div>
              </td>
              <td>
                <span class="text-capitalize">{{ shareholder.shareClass }}</span>
              </td>
              <td>{{ shareholder.sharesHeld }}</td>
              <td>{{ calculateSharePercentage(shareholder.sharesHeld) }}</td>
              <td>{{ formatDate(shareholder.acquisitionDate) }}</td>
              <td>
                <span class="badge rounded-pill" 
                      [class.bg-success]="shareholder.status === 'active'"
                      [class.bg-warning]="shareholder.status === 'transferred'"
                      [class.bg-danger]="shareholder.status === 'deceased'">
                  {{ shareholder.status }}
                </span>
              </td>
              <td>
                <div class="btn-group">
                  <button class="btn btn-link" title="View Details" (click)="viewShareholderDetails(shareholder, $event)">
                    <i class="bi bi-eye"></i>
                  </button>
                  <button class="btn btn-link" title="Edit">
                    <i class="bi bi-pencil"></i>
                  </button>
                  <button class="btn btn-link text-danger" (click)="removeShareholder(i)" title="Remove">
                    <i class="bi bi-trash"></i>
                  </button>
                </div>
              </td>
            </tr>
            <tr *ngIf="shareholders.length === 0">
              <td colspan="7" class="text-center py-4">
                <div class="text-muted">
                  <i class="bi bi-info-circle me-2"></i>
                  No shareholders added yet
                </div>
              </td>
            </tr>
          </tbody>
          <tfoot *ngIf="shareholders.length > 0" class="table-light">
            <tr>
              <td><strong>Total</strong></td>
              <td></td>
              <td><strong>{{ getTotalShares() }}</strong></td>
              <td><strong>100%</strong></td>
              <td colspan="3"></td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>

    <!-- Recent Activities -->
    <div class="card">
      <div class="card-header">
        <h5 class="mb-0">Recent Activities</h5>
      </div>
      <div class="activity-list">
        <div class="activity-item" *ngFor="let activity of recentActivities">
          <div class="activity-icon" [class]="activity.type">
            <i [class]="getActivityIcon(activity.type)"></i>
          </div>
          <div class="activity-content">
            <div class="activity-description">{{ activity.description }}</div>
            <div class="activity-meta">
              <span class="user">{{ activity.user }}</span>
              <span class="time">{{ activity.time }}</span>
            </div>
          </div>
        </div>
        <div *ngIf="!recentActivities?.length" class="text-center py-4">
          <div class="text-muted">No recent activities</div>
        </div>
      </div>
    </div>
  </div>
</div>
