// app/src/components/help/HelpSidebar.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

interface HelpSidebarProps {
  isExpanded?: boolean;
}

const HelpSidebar: React.FC<HelpSidebarProps> = ({ isExpanded = true }) => {
  const navItems = [
    {
      label: 'Overview',
      icon: 'bi-grid',
      route: '/help'
    },
    {
      label: 'Documentation',
      icon: 'bi-book',
      route: '/help/docs'
    },
    {
      label: 'FAQs',
      icon: 'bi-question-circle',
      route: '/help/faqs'
    },
    {
      label: 'Support',
      icon: 'bi-headset',
      route: '/help/support'
    },
    {
      label: 'Tutorials',
      icon: 'bi-play-circle',
      route: '/help/tutorials'
    }
  ];

  return (
    <div className="d-flex flex-column h-100">
      <div className="py-4">
        {isExpanded && (
          <div className="px-4 mb-2">
            <span className="text-uppercase small fw-semibold" style={{ color: 'var(--bs-gray-600)' }}>HELP CENTER</span>
          </div>
        )}
        <ul className="nav flex-column">
          {navItems.map((item) => (
            <li className="nav-item" key={item.route}>
              <NavLink
                to={item.route}
                className={({ isActive }) => `
                  nav-link d-flex align-items-center py-2
                  ${isExpanded ? 'px-4' : 'px-2'}
                  ${isActive ? 'active fw-medium' : ''}
                  ${isActive ? 'text-primary' : ''}
                  ${isActive ? '' : ''}
                  hover-primary
                `}
                end={item.route === '/help'}
              >
                <i className={`bi fs-5 ${isExpanded ? 'me-3' : ''} ${item.icon}`}></i>
                {isExpanded && <span className="small">{item.label}</span>}
              </NavLink>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default HelpSidebar;

// app/src/app/components/help/help-sidebar/help-sidebar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-help-sidebar',
  templateUrl: './help-sidebar.component.html',
  styleUrls: ['./help-sidebar.component.scss'],
  standalone: true,
  imports: [CommonModule, RouterModule]
})
export class HelpSidebarComponent {
  navItems = [
    {
      path: '/help/documentation',
      icon: 'bi-book',
      label: 'Documentation'
    },
    {
      path: '/help/tutorials',
      icon: 'bi-play-circle',
      label: 'Tutorials'
    },
    {
      path: '/help/faqs',
      icon: 'bi-question-circle',
      label: 'FAQs'
    },
    {
      path: '/help/support',
      icon: 'bi-headset',
      label: 'Support'
    },
    {
      path: '/help/community',
      icon: 'bi-people',
      label: 'Community'
    },
    {
      path: '/help/updates',
      icon: 'bi-bell',
      label: 'Updates'
    }
  ];
}

<div class="nav-section">
  <div class="section-header">
    <span>HELP</span>
  </div>
  <ul class="nav-items">
    <li *ngFor="let item of navItems">
      <a [routerLink]="item.path" routerLinkActive="active">
        <i class="bi" [class]="item.icon"></i>
        <span class="nav-label">{{item.label}}</span>
      </a>
    </li>
  </ul>
</div>
