// app/src/app/components/statutory/beneficial-owners/beneficial-owners.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { NgbModal, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Router } from '@angular/router';
import { Subject, Observable, of } from 'rxjs';
import { takeUntil, catchError, finalize, switchMap, map } from 'rxjs/operators';

import { CreateOwnerModalComponent } from './modal/create-owner-modal.component';
import { EditOwnerModalComponent } from './modal/edit-owner-modal.component';
import { ViewOwnerModalComponent } from './modal/view-owner-modal.component';
import { ConfirmModalComponent } from './modal/confirm-modal.component';

import { BeneficialOwnerService } from '../../../services/statutory/beneficial-owner.service';
import { CompanyService } from '../../../services/settings/company.service';
import { ActivityService } from '../../../services/statutory/activity.service';
import { AuthService } from '../../../services/auth/auth.service';

import { BeneficialOwner, Activity, ActivityResponse } from '../statutory.types';

type ControlValue = 'shares' | 'voting' | 'appointment' | 'influence' | 'trust' | 'partnership';

interface ControlType {
  value: ControlValue;
  label: string;
}

@Component({
  selector: 'app-beneficial-owners',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NgbModule,
    CreateOwnerModalComponent,
    EditOwnerModalComponent,
    ViewOwnerModalComponent,
    ConfirmModalComponent
  ],
  template: `
    <div class="container-fluid p-4">
      <!-- Header -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 class="h3 mb-2">Beneficial Owners Register</h1>
          <p class="text-muted mb-0">Record and manage company beneficial owners and their control details</p>
        </div>
        <div>
          <button class="btn btn-primary d-inline-flex align-items-center gap-2" (click)="openAddOwnerModal()">
            <i class="bi bi-plus-lg"></i>
            <span>Add Beneficial Owner</span>
          </button>
        </div>
      </div>

      <!-- Metrics -->
      <div class="row g-3 mb-4">
        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Active Owners</span>
                <i class="bi bi-people fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getActiveOwnersCount() }}</h3>
              <small class="text-muted">Currently registered owners</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Significant Control</span>
                <i class="bi bi-diagram-3 fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getSignificantControlCount() }}</h3>
              <small class="text-muted">Owners with >25% shares</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Voting Rights</span>
                <i class="bi bi-check-circle fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getVotingRightsCount() }}</h3>
              <small class="text-muted">Owners with voting rights</small>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span class="text-muted">Average Ownership</span>
                <i class="bi bi-pie-chart fs-4 text-primary"></i>
              </div>
              <h3 class="mb-0">{{ getAverageOwnership() }}%</h3>
              <small class="text-muted">Average ownership percentage</small>
            </div>
          </div>
        </div>
      </div>

      <!-- Owners Table -->
      <div class="card mb-4">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Beneficial Owners</h5>
          <button class="btn btn-light btn-sm d-inline-flex align-items-center gap-2 border" (click)="toggleShowAll()">
            <i [class]="showAll ? 'bi bi-funnel' : 'bi bi-funnel-fill'" class="text-primary"></i>
            <span>{{ showAll ? 'Show Active Only' : 'Show All Owners' }}</span>
          </button>
        </div>
        <div class="table-responsive">
          <table class="table table-hover mb-0">
            <thead class="bg-light">
              <tr>
                <th class="text-uppercase small fw-semibold text-secondary">Name</th>
                <th class="text-uppercase small fw-semibold text-secondary">Control Types</th>
                <th class="text-uppercase small fw-semibold text-secondary">Ownership</th>
                <th class="text-uppercase small fw-semibold text-secondary">Registered</th>
                <th class="text-uppercase small fw-semibold text-secondary">Status</th>
                <th class="text-uppercase small fw-semibold text-secondary">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let owner of getFilteredOwners()">
                <td>
                  <div class="d-flex align-items-center gap-2">
                    <i class="bi bi-person-circle text-secondary"></i>
                    <a href="#" class="text-decoration-none" (click)="viewOwner(owner, $event)">
                      {{ getFullName(owner) }}
                    </a>
                  </div>
                </td>
                <td>
                  <div class="d-flex flex-wrap gap-1">
                    <span *ngFor="let control of owner.natureOfControl" class="badge text-bg-primary">
                      {{ getControlLabel(control) }}
                    </span>
                  </div>
                </td>
                <td>{{ owner.ownershipPercentage }}%</td>
                <td>{{ formatDate(owner.registrationDate) }}</td>
                <td>
                  <span [class]="'badge ' + (owner.status === 'Active' ? 'text-bg-success' : 'text-bg-secondary')">
                    {{ owner.status }}
                  </span>
                </td>
                <td>
                  <div class="btn-group">
                    <button class="btn btn-link btn-sm text-body px-2" (click)="viewOwner(owner)" title="View Details">
                      <i class="bi bi-eye"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-body px-2" (click)="editOwner(owner)" title="Edit">
                      <i class="bi bi-pencil"></i>
                    </button>
                    <button class="btn btn-link btn-sm text-danger px-2" (click)="removeOwner(owner)" title="Remove">
                      <i class="bi bi-trash"></i>
                    </button>
                  </div>
                </td>
              </tr>
              <tr *ngIf="getFilteredOwners().length === 0">
                <td colspan="6" class="text-center py-4 text-muted">
                  <i class="bi bi-info-circle me-2"></i>
                  No beneficial owners found
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Recent Activities -->
      <div class="card">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
          <h5 class="mb-0">Recent Activities</h5>
          <button class="btn btn-link p-0 text-decoration-none" (click)="refreshData()">
            <i class="bi bi-arrow-clockwise me-1"></i>
            <span>Refresh</span>
          </button>
        </div>
        <div class="card-body">
          <div class="list-group list-group-flush">
            <div class="list-group-item px-0" *ngFor="let activity of recentActivities">
              <div class="d-flex align-items-start gap-3">
                <div class="bg-light rounded p-2">
                  <i [class]="getActivityIcon(activity.type)"></i>
                </div>
                <div>
                  <p class="mb-1">{{ activity.description }}</p>
                  <div class="d-flex align-items-center gap-2 small">
                    <span class="text-primary">{{ activity.user }}</span>
                    <span class="text-muted">{{ activity.time }}</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center py-4 text-muted" *ngIf="recentActivities.length === 0">
              <i class="bi bi-info-circle me-2"></i>
              No recent activities
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class BeneficialOwnersComponent implements OnInit, OnDestroy {
  owners: BeneficialOwner[] = [];
  showAll = false;
  recentActivities: Activity[] = [];
  loading = false;
  error: string | null = null;
  private destroy$ = new Subject<void>();

  controlTypes: ControlType[] = [
    { value: 'shares', label: 'Shares' },
    { value: 'voting', label: 'Voting' },
    { value: 'appointment', label: 'Appointment' },
    { value: 'influence', label: 'Influence' },
    { value: 'trust', label: 'Trust' },
    { value: 'partnership', label: 'Partnership' }
  ];

  constructor(
    private modalService: NgbModal,
    private router: Router,
    private beneficialOwnerService: BeneficialOwnerService,
    private companyService: CompanyService,
    private activityService: ActivityService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.refreshData();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  refreshData(): void {
    // Get current company's beneficial owners
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    this.loading = true;
    this.error = null;

    // First get company details
    this.companyService.getCompany(companyId).pipe(
      takeUntil(this.destroy$),
      switchMap(company => 
        this.beneficialOwnerService.getBeneficialOwners(companyId, this.showAll ? undefined : 'Active').pipe(
          map(owners => owners.map(o => ({ ...o, company })))
        )
      ),
      catchError(error => {
        console.error('Error loading beneficial owners:', error);
        this.error = 'Failed to load beneficial owners. Please try again.';
        return of([]);
      }),
      finalize(() => this.loading = false)
    ).subscribe(ownersArrays => {
      this.owners = ownersArrays.flat();
      this.loadActivities(companyId);
    });
  }

  private loadActivities(companyId: string): void {
    this.activityService.getActivities(companyId, {
      entityType: 'beneficial-owner',
      limit: 10
    }).pipe(
      catchError(error => {
        console.error('Error loading activities:', error);
        return of({ activities: [], total: 0 } as ActivityResponse);
      })
    ).subscribe(response => {
      this.recentActivities = response.activities;
    });
  }

  openAddOwnerModal(): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(CreateOwnerModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });

    modalRef.result.then(
      (newOwner: BeneficialOwner) => {
        this.beneficialOwnerService.createBeneficialOwner(companyId, newOwner)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to create beneficial owner. Please try again.';
              console.error('Error creating beneficial owner:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(owner => {
              if (owner) {
                return this.addActivity(companyId, {
                  type: 'added',
                  entityType: 'beneficial-owner',
                  entityId: owner.id,
                  description: `${this.getFullName(owner)} added as beneficial owner with ${owner.ownershipPercentage}% ownership`,
                  user: 'System'
                }).pipe(map(() => owner));
              }
              return of(null);
            })
          )
          .subscribe(owner => {
            if (owner) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  viewOwner(owner: BeneficialOwner, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    
    const modalRef = this.modalService.open(ViewOwnerModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.owner = {...owner};
    
    modalRef.result.then(
      (result: { action: string; owner: BeneficialOwner } | undefined) => {
        if (result?.action === 'edit') {
          this.editOwner(result.owner);
        }
      },
      () => {} // Modal dismissed
    );
  }

  editOwner(owner: BeneficialOwner): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(EditOwnerModalComponent, {
      size: 'lg',
      backdrop: 'static'
    });
    
    modalRef.componentInstance.owner = {...owner};
    
    modalRef.result.then(
      (updatedOwner: BeneficialOwner) => {
        this.beneficialOwnerService.updateBeneficialOwner(companyId, owner.id, updatedOwner)
          .pipe(
            catchError(error => {
              const errorMsg = error.error?.message || 'Failed to update beneficial owner. Please try again.';
              console.error('Error updating beneficial owner:', error);
              this.error = errorMsg;
              return of(null);
            }),
            switchMap(result => {
              if (result) {
                return this.addActivity(companyId, {
                  type: 'updated',
                  entityType: 'beneficial-owner',
                  entityId: owner.id,
                  description: `${this.getFullName(owner)}'s details updated`,
                  user: 'System'
                }).pipe(map(() => result));
              }
              return of(null);
            })
          )
          .subscribe(result => {
            if (result) {
              this.refreshData();
            }
          });
      },
      () => {} // Modal dismissed
    );
  }

  removeOwner(owner: BeneficialOwner): void {
    const user = this.authService.currentUserValue;
    const companyId = user?.companyId;
    if (!companyId) {
      this.error = 'No company selected';
      return;
    }

    const modalRef = this.modalService.open(ConfirmModalComponent, {
      size: 'sm',
      backdrop: 'static'
    });

    modalRef.componentInstance.title = 'Confirm Removal';
    modalRef.componentInstance.message = `Are you sure you want to remove ${this.getFullName(owner)} from the beneficial owners register?`;
    modalRef.componentInstance.confirmButtonText = 'Remove';
    modalRef.componentInstance.confirmButtonClass = 'btn-danger';

    modalRef.result.then(
      (result: boolean) => {
        if (result === true) {
          this.beneficialOwnerService.deleteBeneficialOwner(companyId, owner.id)
            .pipe(
              catchError(error => {
                const errorMsg = error.error?.message || 'Failed to remove beneficial owner. Please try again.';
                console.error('Error removing beneficial owner:', error);
                this.error = errorMsg;
                return of(null);
              }),
              switchMap(() => {
                return this.addActivity(companyId, {
                  type: 'removed',
                  entityType: 'beneficial-owner',
                  entityId: owner.id,
                  description: `${this.getFullName(owner)} removed from beneficial owners register`,
                  user: 'System'
                });
              })
            )
            .subscribe(activity => {
              if (activity) {
                this.refreshData();
              }
            });
        }
      },
      () => {} // Modal dismissed
    );
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-GB');
  }

  getFullName(owner: BeneficialOwner): string {
    return `${owner.title} ${owner.firstName} ${owner.lastName}`;
  }

  getControlLabel(value: string): string {
    const control = this.controlTypes.find(c => c.value === value as ControlValue);
    return control?.label || value;
  }

  toggleShowAll(): void {
    this.showAll = !this.showAll;
    this.refreshData();
  }

  getFilteredOwners(): BeneficialOwner[] {
    return this.showAll 
      ? this.owners 
      : this.owners.filter(o => o.status === 'Active');
  }

  getActiveOwnersCount(): number {
    return this.owners.filter(o => o.status === 'Active').length;
  }

  getSignificantControlCount(): number {
    return this.owners.filter(o => 
      o.status === 'Active' && o.ownershipPercentage > 25
    ).length;
  }

  getVotingRightsCount(): number {
    return this.owners.filter(o => 
      o.status === 'Active' && o.natureOfControl.includes('voting')
    ).length;
  }

  getAverageOwnership(): string {
    const activeOwners = this.owners.filter(o => o.status === 'Active');
    if (activeOwners.length === 0) return '0';

    const totalPercentage = activeOwners.reduce((sum, o) => sum + o.ownershipPercentage, 0);
    return (totalPercentage / activeOwners.length).toFixed(1);
  }

  getActivityIcon(type: Activity['type']): string {
    switch (type) {
      case 'added':
        return 'bi bi-person-plus';
      case 'updated':
        return 'bi bi-pencil';
      case 'removed':
        return 'bi bi-trash';
      case 'status_changed':
        return 'bi bi-arrow-repeat';
      default:
        return 'bi bi-activity';
    }
  }

  private addActivity(companyId: string, activity: Omit<Activity, 'id' | 'companyId' | 'time'>): Observable<Activity | null> {
    return this.activityService.createActivity(companyId, {
      ...activity,
      companyId,
      time: new Date().toISOString()
    }).pipe(
      catchError(error => {
        console.error('Error creating activity:', error);
        return of(null);
      })
    );
  }
}

<div class="container-fluid p-4">
  <div class="row mb-4">
    <div class="col">
      <h1 class="mb-0">Beneficial Owners Register</h1>
      <p class="text-muted">Record and manage company's persons with significant control (PSC)</p>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Add Beneficial Owner</h5>
          <form [formGroup]="ownerForm" (ngSubmit)="onSubmit()">
            <div class="mb-3">
              <label class="form-label">Full Name</label>
              <input type="text" class="form-control" formControlName="name" placeholder="Enter full name">
            </div>

            <div class="mb-3">
              <label class="form-label">Nationality</label>
              <input type="text" class="form-control" formControlName="nationality" placeholder="Enter nationality">
            </div>

            <div class="mb-3">
              <label class="form-label">Date of Birth</label>
              <input type="date" class="form-control" formControlName="dateOfBirth">
            </div>

            <div class="mb-3">
              <label class="form-label">Address</label>
              <textarea class="form-control" formControlName="address" rows="3" placeholder="Enter full address"></textarea>
            </div>

            <div class="mb-3">
              <label class="form-label">Ownership Percentage</label>
              <div class="input-group">
                <input type="number" class="form-control" formControlName="ownershipPercentage" placeholder="Enter percentage">
                <span class="input-group-text">%</span>
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Nature of Control</label>
              <select class="form-select" formControlName="natureOfControl">
                <option value="">Select control type</option>
                <option *ngFor="let type of controlTypes" [value]="type">{{ type }}</option>
              </select>
            </div>

            <div class="mb-3">
              <label class="form-label">Start Date</label>
              <input type="date" class="form-control" formControlName="startDate">
            </div>

            <div class="mb-3">
              <label class="form-label">End Date (Optional)</label>
              <input type="date" class="form-control" formControlName="endDate">
            </div>

            <div class="mb-3">
              <label class="form-label">Notification Date</label>
              <input type="date" class="form-control" formControlName="notificationDate">
            </div>

            <div class="mb-3">
              <label class="form-label">PSC Register Number</label>
              <input type="text" class="form-control" formControlName="pscRegisterNumber" placeholder="Enter PSC register number">
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="!ownerForm.valid">
              Add Beneficial Owner
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4">Beneficial Owners</h5>
          
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Nationality</th>
                  <th>Ownership %</th>
                  <th>Control Type</th>
                  <th>Start Date</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let owner of owners; let i = index">
                  <td>{{ owner.name }}</td>
                  <td>{{ owner.nationality }}</td>
                  <td>{{ owner.ownershipPercentage }}%</td>
                  <td>{{ owner.natureOfControl }}</td>
                  <td>{{ formatDate(owner.startDate) }}</td>
                  <td>
                    <span class="badge" [class.bg-success]="!owner.endDate" [class.bg-danger]="owner.endDate">
                      {{ owner.endDate ? 'Ceased' : 'Active' }}
                    </span>
                  </td>
                  <td>
                    <button class="btn btn-sm btn-outline-danger" (click)="removeOwner(i)">
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
                <tr *ngIf="owners.length === 0">
                  <td colspan="7" class="text-center py-4 text-muted">
                    No beneficial owners recorded yet
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// app/src/components/statutory/sections/beneficial-owners/BeneficialOwners.tsx
import React, { useState, useEffect } from 'react';
import BeneficialOwnerModal from './BeneficialOwnerModal';
import ImportBeneficialOwnerModal from './ImportBeneficialOwnerModal';
import api from '../../../../services/api';
import { useAuth } from '../../../../contexts/AuthContext';
import { Table, Button, Badge, Row, Col, Card, Dropdown } from 'react-bootstrap';
import { FaPlus, FaEdit, FaFileImport, FaUsers, FaUserCheck, FaUserMinus, FaClock, FaTrash, FaFileExport, FaFilePdf, FaFileExcel } from 'react-icons/fa';

interface BeneficialOwner {
  id?: string;
  title: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  nationality: string;
  address: string;
  email: string;
  phone: string;
  natureOfControl: string[];
  ownershipPercentage: number;
  registrationDate: string;
  status: 'Active' | 'Inactive' | 'Archived';
  description?: string;
  company?: {
    name: string;
    legalName: string;
  };
}

interface Activity {
  id: string;
  type: 'added' | 'updated' | 'removed' | 'status_changed';
  entityType: string;
  entityId: string;
  description: string;
  user: string;
  time: string;
}

const BeneficialOwners: React.FC = () => {
  const timelineStyles = {
    timeline: {
      position: 'relative' as const,
      padding: 0,
      margin: 0,
      listStyle: 'none'
    },
    timelineItem: {
      position: 'relative' as const,
      borderLeft: '2px solid #e9ecef',
      marginLeft: '1rem',
      paddingLeft: '1.5rem'
    }
  };

  const [owners, setOwners] = useState<BeneficialOwner[]>([]);
  const [recentActivities, setRecentActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [activitiesLoading, setActivitiesLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | 'Active' | 'Inactive' | 'Archived'>('All');
  const { user } = useAuth();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [selectedOwner, setSelectedOwner] = useState<BeneficialOwner | undefined>(undefined);

  useEffect(() => {
    fetchOwners();
    fetchRecentActivities();
  }, [statusFilter]);

  const fetchRecentActivities = async () => {
    try {
      setActivitiesLoading(true);
      const response = await api.get(`/statutory/activities/${user?.companyId}?entityType=beneficial-owner&limit=5`);
      if (response.data?.activities) {
        setRecentActivities(response.data.activities);
      }
    } catch (err) {
      console.error('Error fetching recent activities:', err);
    } finally {
      setActivitiesLoading(false);
    }
  };

  const fetchOwners = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/statutory/beneficial-owners/${user?.companyId}?status=${statusFilter}`);
      if (Array.isArray(response.data)) {
        setOwners(response.data);
      } else {
        setOwners([]);
        console.error('Expected array of beneficial owners but got:', response.data);
      }
      setError('');
    } catch (err) {
      setError('Failed to load beneficial owners');
      console.error('Error fetching beneficial owners:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (type: 'pdf' | 'excel') => {
    try {
      const response = await api.get(`/statutory/beneficial-owners/${user?.companyId}/export/${type}`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `beneficial-owners.${type === 'pdf' ? 'pdf' : 'xlsx'}`);
      
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Error exporting beneficial owners:', error);
      alert('Failed to export beneficial owners. Please try again.');
    }
  };

  const handleAddOwner = () => {
    setSelectedOwner(undefined);
    setShowAddModal(true);
  };

  const handleEditOwner = (owner: BeneficialOwner) => {
    setSelectedOwner(owner);
    setShowAddModal(true);
  };

  const handleDeleteOwner = async (owner: BeneficialOwner) => {
    if (window.confirm(`Are you sure you want to delete ${owner.firstName} ${owner.lastName}? This action cannot be undone.`)) {
      try {
        await api.delete(`/statutory/beneficial-owners/${user?.companyId}/${owner.id}`);
        fetchOwners();
        fetchRecentActivities();
      } catch (error) {
        console.error('Error deleting beneficial owner:', error);
        alert('Failed to delete beneficial owner. Please try again.');
      }
    }
  };

  const handleModalSuccess = () => {
    fetchOwners();
    fetchRecentActivities();
  };

  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="d-flex justify-content-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <BeneficialOwnerModal
        show={showAddModal}
        onHide={() => setShowAddModal(false)}
        owner={selectedOwner}
        onSuccess={handleModalSuccess}
      />
      {user?.companyId && (
        <ImportBeneficialOwnerModal
          show={showImportModal}
          onHide={() => setShowImportModal(false)}
          onSuccess={handleModalSuccess}
          companyId={user.companyId}
        />
      )}
      <div className="container-fluid py-4">
        {/* Header */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <div>
            <h1 className="h3 mb-0">Beneficial Owners Register</h1>
            <p className="text-muted mb-0">Record and manage company beneficial owners and their ownership details</p>
          </div>
          <div className="d-flex">
            <Dropdown className="me-2">
              <Dropdown.Toggle variant="outline-primary" id="export-dropdown">
                <FaFileExport className="me-2" /> Export
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item onClick={() => handleExport('pdf')}>
                  <FaFilePdf className="me-2" /> Export as PDF
                </Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport('excel')}>
                  <FaFileExcel className="me-2" /> Export as Excel
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
            <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
              <FaFileImport className="me-2" /> Import
            </Button>
            <Button variant="primary" onClick={handleAddOwner}>
              <FaPlus className="me-2" /> Add Beneficial Owner
            </Button>
          </div>
        </div>

        {error && (
          <div className="alert alert-danger mb-4" role="alert">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <Row className="mb-4">
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Total Beneficial Owners</div>
                    <h3 className="mb-0">{owners.length}</h3>
                  </div>
                  <div className="bg-primary bg-opacity-10 p-3 rounded">
                    <FaUsers className="text-primary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Active Owners</div>
                    <h3 className="mb-0">{owners.filter(o => o.status === 'Active').length}</h3>
                  </div>
                  <div className="bg-success bg-opacity-10 p-3 rounded">
                    <FaUserCheck className="text-success" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="h-100">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="text-muted mb-1">Inactive/Archived</div>
                    <h3 className="mb-0">{owners.filter(o => o.status !== 'Active').length}</h3>
                  </div>
                  <div className="bg-secondary bg-opacity-10 p-3 rounded">
                    <FaUserMinus className="text-secondary" size={24} />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>

        {/* Beneficial Owners Table */}
        <div className="card mb-4">
          <div className="card-body">
            <div className="d-flex justify-content-end mb-3">
              <div className="btn-group">
                <Button
                  variant={statusFilter === 'All' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('All')}
                >
                  All
                </Button>
                <Button
                  variant={statusFilter === 'Active' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Active')}
                >
                  Active
                </Button>
                <Button
                  variant={statusFilter === 'Inactive' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Inactive')}
                >
                  Inactive
                </Button>
                <Button
                  variant={statusFilter === 'Archived' ? 'primary' : 'outline-primary'}
                  onClick={() => setStatusFilter('Archived')}
                >
                  Archived
                </Button>
              </div>
            </div>
            <Table responsive hover className="align-middle">
              <thead className="bg-light">
                <tr>
                  <th>Name</th>
                  <th>Nature of Control</th>
                  <th>Ownership %</th>
                  <th>Registration Date</th>
                  <th>Status</th>
                  {user?.role === 'super_admin' && <th>Company</th>}
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {owners.map((owner) => (
                  <tr key={owner.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <div>
                          <div className="fw-bold">{`${owner.title} ${owner.firstName} ${owner.lastName}`}</div>
                          <div className="text-muted small">{owner.nationality}</div>
                        </div>
                      </div>
                    </td>
                    <td>{owner.natureOfControl.join(', ')}</td>
                    <td>{owner.ownershipPercentage}%</td>
                    <td>{new Date(owner.registrationDate).toLocaleDateString('en-IE', {
                      day: '2-digit',
                      month: '2-digit',
                      year: 'numeric'
                    })}</td>
                    <td>
                      <Badge bg={
                        owner.status === 'Active' ? 'success' :
                        owner.status === 'Inactive' ? 'warning' :
                        'secondary'
                      }>
                        {owner.status}
                      </Badge>
                    </td>
                    {user?.role === 'super_admin' && (
                      <td>{owner.company?.name || owner.company?.legalName}</td>
                    )}
                    <td className="text-end">
                      <Button
                        variant="link"
                        className="p-0 me-3"
                        onClick={() => handleEditOwner(owner)}
                      >
                        <FaEdit className="text-primary" />
                      </Button>
                      <Button
                        variant="link"
                        className="p-0"
                        onClick={() => handleDeleteOwner(owner)}
                      >
                        <FaTrash className="text-danger" />
                      </Button>
                    </td>
                  </tr>
                ))}
                {owners.length === 0 && (
                  <tr>
                    <td colSpan={user?.role === 'super_admin' ? 7 : 6} className="text-center py-5">
                      <div className="d-flex flex-column align-items-center">
                        <div className="bg-light p-4 rounded-circle mb-3">
                          <FaUsers className="text-muted" size={32} />
                        </div>
                        <h5 className="text-muted mb-2">No Beneficial Owners Found</h5>
                        <p className="text-muted mb-4">Get started by adding your first beneficial owner or importing data</p>
                        <div>
                          <Button variant="outline-primary" className="me-2" onClick={() => setShowImportModal(true)}>
                            <FaFileImport className="me-2" /> Import Beneficial Owners
                          </Button>
                          <Button variant="primary" onClick={handleAddOwner}>
                            <FaPlus className="me-2" /> Add Beneficial Owner
                          </Button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </div>

        {/* Recent Activities */}
        <Card>
          <Card.Body>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5 className="mb-0">
                <FaClock className="me-2" />
                Recent Activities
              </h5>
            </div>
            {activitiesLoading ? (
              <div className="text-center py-4">
                <div className="spinner-border spinner-border-sm text-primary"></div>
                <p className="text-muted small mt-2 mb-0">Loading activities...</p>
              </div>
            ) : recentActivities.length > 0 ? (
              <div style={timelineStyles.timeline}>
                {recentActivities.map((activity, index) => (
                  <div key={index} style={timelineStyles.timelineItem} className="pb-3">
                    <div className="d-flex">
                      <div className="me-3">
                        <Badge bg="light" className="p-2">
                          {activity.type === 'added' ? (
                            <FaPlus className="text-success" />
                          ) : activity.type === 'updated' ? (
                            <FaEdit className="text-primary" />
                          ) : activity.type === 'removed' ? (
                            <FaTrash className="text-danger" />
                          ) : (
                            <FaEdit className="text-primary" />
                          )}
                        </Badge>
                      </div>
                      <div>
                        <p className="mb-0">{activity.description}</p>
                        <small className="text-muted">
                          {new Date(activity.time).toLocaleString('en-IE', {
                            day: '2-digit',
                            month: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </small>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted mb-0">No recent activities</p>
            )}
          </Card.Body>
        </Card>
      </div>
    </>
  );
};

export default BeneficialOwners;
